{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fallibleParsedData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forceContinue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXRoot","text":"GPXRoot"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"forceContinue","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"type":"codeVoice","code":"true"},{"type":"text","text":", parser will continue parsing even if non XML-based issues like invalid coordinates have occurred"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"GPXError"},{"type":"text","text":" errors if an incident has occurred while midway or after parsing the GPX file."}]}],"type":"aside","name":"Throws"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxparser\/fallibleparseddata(forcecontinue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/fallibleParsedData(forceContinue:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Starts parsing, returns parsed "},{"type":"codeVoice","code":"GPXRoot"},{"type":"text","text":" when done."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fallibleParsedData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forceContinue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"GPXRoot","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXRoot"},{"kind":"text","text":"?"}],"title":"fallibleParsedData(forceContinue:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:7CoreGPX9GPXParserC18fallibleParsedData13forceContinueAA7GPXRootCSgSb_tKF","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot":{"role":"symbol","title":"GPXRoot","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRoot"}],"abstract":[{"type":"text","text":"Creation of a GPX file or GPX formatted string starts here"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRoot"}],"url":"\/documentation\/coregpx\/gpxroot"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser":{"role":"symbol","title":"GPXParser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXParser"}],"abstract":[{"type":"text","text":"An event-driven parser (SAX parser), currently parses GPX v1.1 files only."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXParser"}],"url":"\/documentation\/coregpx\/gpxparser"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser/fallibleParsedData(forceContinue:)":{"role":"symbol","title":"fallibleParsedData(forceContinue:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fallibleParsedData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forceContinue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"GPXRoot","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXRoot"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Starts parsing, returns parsed "},{"type":"codeVoice","code":"GPXRoot"},{"type":"text","text":" when done."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/fallibleParsedData(forceContinue:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxparser\/fallibleparseddata(forcecontinue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoot\/title","value":"GPXRoot"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoot\/fragments","value":[{"kind":"identifier","text":"GPXRoot"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser\/title","value":"GPXParser"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser\/fragments","value":[{"kind":"identifier","text":"GPXParser"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}