{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"legacyParsingData"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLegacyRoot","text":"GPXLegacyRoot"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxparser\/legacyparsingdata()"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/legacyParsingData()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Starts parsing, returns parsed "},{"type":"codeVoice","code":"GPXRoot"},{"type":"text","text":" when done."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"legacyParsingData"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GPXLegacyRoot","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLegacyRoot"},{"kind":"text","text":"?"}],"title":"legacyParsingData()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:7CoreGPX9GPXParserC17legacyParsingDataAA13GPXLegacyRootCSgyF","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser":{"role":"symbol","title":"GPXParser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXParser"}],"abstract":[{"type":"text","text":"An event-driven parser (SAX parser), currently parses GPX v1.1 files only."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXParser"}],"url":"\/documentation\/coregpx\/gpxparser"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser/legacyParsingData()":{"role":"symbol","title":"legacyParsingData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"legacyParsingData"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GPXLegacyRoot","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLegacyRoot"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Starts parsing, returns parsed "},{"type":"codeVoice","code":"GPXRoot"},{"type":"text","text":" when done."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/legacyParsingData()","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxparser\/legacyparsingdata()"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot":{"role":"symbol","title":"GPXLegacyRoot","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyRoot"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyRoot"}],"url":"\/documentation\/coregpx\/gpxlegacyroot"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser\/title","value":"GPXParser"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser\/fragments","value":[{"kind":"identifier","text":"GPXParser"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoot\/title","value":"GPXLegacyRoot"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoot\/fragments","value":[{"kind":"identifier","text":"GPXLegacyRoot"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}