{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lossyParsing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCompression","preciseIdentifier":"s:7CoreGPX14GPXCompressionC","text":"GPXCompression"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCompression\/lossyTypes","preciseIdentifier":"s:7CoreGPX14GPXCompressionC10lossyTypesO","text":"lossyTypes"},{"kind":"text","text":", "},{"kind":"externalParam","text":"affecting"},{"kind":"text","text":" "},{"kind":"internalParam","text":"types"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCompression","preciseIdentifier":"s:7CoreGPX14GPXCompressionC","text":"GPXCompression"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCompression\/lossyOptions","preciseIdentifier":"s:7CoreGPX14GPXCompressionC12lossyOptionsO","text":"lossyOptions"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXRoot","text":"GPXRoot"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Great for basic direct compression needs."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxparser\/lossyparsing(type:affecting:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/lossyParsing(type:affecting:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Parse GPX file, while lossy compressing it straight away, post-parsing."}],"kind":"symbol","metadata":{"role":"symbol","title":"lossyParsing(type:affecting:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lossyParsing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXCompression","preciseIdentifier":"s:7CoreGPX14GPXCompressionC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"lossyTypes","preciseIdentifier":"s:7CoreGPX14GPXCompressionC10lossyTypesO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"affecting"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXCompression","preciseIdentifier":"s:7CoreGPX14GPXCompressionC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"lossyOptions","preciseIdentifier":"s:7CoreGPX14GPXCompressionC12lossyOptionsO"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"GPXRoot","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXRoot"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"s:7CoreGPX9GPXParserC12lossyParsing4type9affectingAA7GPXRootCSgAA14GPXCompressionC0D5TypesO_SayAK0D7OptionsOGtF","extendedModule":"CoreGPX","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXCompression/lossyOptions":{"role":"symbol","title":"GPXCompression.lossyOptions","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"lossyOptions"}],"abstract":[{"type":"text","text":"Selectable scope of removal of points."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCompression\/lossyOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lossyOptions"}],"url":"\/documentation\/coregpx\/gpxcompression\/lossyoptions"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot":{"role":"symbol","title":"GPXRoot","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRoot"}],"abstract":[{"type":"text","text":"Creation of a GPX file or GPX formatted string starts here"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRoot"}],"url":"\/documentation\/coregpx\/gpxroot"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser":{"role":"symbol","title":"GPXParser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXParser"}],"abstract":[{"type":"text","text":"An event-driven parser (SAX parser), currently parses GPX v1.1 files only."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXParser"}],"url":"\/documentation\/coregpx\/gpxparser"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXCompression/lossyTypes":{"role":"symbol","title":"GPXCompression.lossyTypes","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"lossyTypes"}],"abstract":[{"type":"text","text":"Currently supported types of compression."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCompression\/lossyTypes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lossyTypes"}],"url":"\/documentation\/coregpx\/gpxcompression\/lossytypes"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXCompression":{"role":"symbol","title":"GPXCompression","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXCompression"}],"abstract":[{"type":"text","text":"Simple class for some basic lossy compression."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCompression","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXCompression"}],"url":"\/documentation\/coregpx\/gpxcompression"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser/lossyParsing(type:affecting:)":{"role":"symbol","title":"lossyParsing(type:affecting:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lossyParsing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXCompression","preciseIdentifier":"s:7CoreGPX14GPXCompressionC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"lossyTypes","preciseIdentifier":"s:7CoreGPX14GPXCompressionC10lossyTypesO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"affecting"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXCompression","preciseIdentifier":"s:7CoreGPX14GPXCompressionC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"lossyOptions","preciseIdentifier":"s:7CoreGPX14GPXCompressionC12lossyOptionsO"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"GPXRoot","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXRoot"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Parse GPX file, while lossy compressing it straight away, post-parsing."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/lossyParsing(type:affecting:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxparser\/lossyparsing(type:affecting:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoot\/title","value":"GPXRoot"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoot\/fragments","value":[{"kind":"identifier","text":"GPXRoot"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser\/title","value":"GPXParser"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser\/fragments","value":[{"kind":"identifier","text":"GPXParser"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}