{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"parser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"XMLParser","preciseIdentifier":"c:objc(cs)NSXMLParser"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartElement"},{"kind":"text","text":" "},{"kind":"internalParam","text":"elementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"namespaceURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"qualifiedName"},{"kind":"text","text":" "},{"kind":"internalParam","text":"qName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"attributes"},{"kind":"text","text":" "},{"kind":"internalParam","text":"attributeDict"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"] = [:])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxparser\/parser(_:didstartelement:namespaceuri:qualifiedname:attributes:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/coregpx\/gpxparser\/parser(_:didstartelement:namespaceuri:qualifiedname:attributes:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Default XML Parser Delegate’s start element ("},{"type":"text","text":") callback."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"parser:didStartElement:namespaceURI:qualifiedName:attributes:"}],"role":"symbol","title":"parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"XMLParser","preciseIdentifier":"c:objc(cs)NSXMLParser"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartElement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"namespaceURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"qualifiedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"attributes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:@CM@CoreGPX@objc(cs)GPXParser(im)parser:didStartElement:namespaceURI:qualifiedName:attributes:","extendedModule":"CoreGPX","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/XMLParserDelegate-Implementations"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser/XMLParserDelegate-Implementations":{"role":"collectionGroup","title":"XMLParserDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/XMLParserDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/coregpx\/gpxparser\/xmlparserdelegate-implementations"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser/parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)":{"role":"symbol","title":"parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"XMLParser","preciseIdentifier":"c:objc(cs)NSXMLParser"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartElement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"namespaceURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"qualifiedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"attributes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Default XML Parser Delegate’s start element ("},{"type":"text","text":") callback."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parser:didStartElement:namespaceURI:qualifiedName:attributes:"}],"url":"\/documentation\/coregpx\/gpxparser\/parser(_:didstartelement:namespaceuri:qualifiedname:attributes:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser":{"role":"symbol","title":"GPXParser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXParser"}],"abstract":[{"type":"text","text":"An event-driven parser (SAX parser), currently parses GPX v1.1 files only."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXParser"}],"url":"\/documentation\/coregpx\/gpxparser"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"parser:didStartElement:namespaceURI:qualifiedName:attributes:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parser:didStartElement:namespaceURI:qualifiedName:attributes:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"parser:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSXMLParser","preciseIdentifier":"c:objc(cs)NSXMLParser"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"parser"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartElement:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"elementName"},{"kind":"text","text":" "},{"kind":"identifier","text":"namespaceURI:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"namespaceURI"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualifiedName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"qName"},{"kind":"text","text":" "},{"kind":"identifier","text":"attributes:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"attributeDict"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser~1parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)\/title","value":"parser:didStartElement:namespaceURI:qualifiedName:attributes:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser~1parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parser:didStartElement:namespaceURI:qualifiedName:attributes:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser\/title","value":"GPXParser"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser\/fragments","value":[{"kind":"identifier","text":"GPXParser"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}