{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"parser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"XMLParser","preciseIdentifier":"c:objc(cs)NSXMLParser"},{"kind":"text","text":", "},{"kind":"externalParam","text":"parseErrorOccurred"},{"kind":"text","text":" "},{"kind":"internalParam","text":"parseError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxparser\/parser(_:parseerroroccurred:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/coregpx\/gpxparser\/parser(_:parseerroroccurred:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/parser(_:parseErrorOccurred:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Handling of XML parser’s thrown error. (if there is any)"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"XMLParser","preciseIdentifier":"c:objc(cs)NSXMLParser"},{"kind":"text","text":", "},{"kind":"externalParam","text":"parseErrorOccurred"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"title":"parser(_:parseErrorOccurred:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@CoreGPX@objc(cs)GPXParser(im)parser:parseErrorOccurred:","modules":[{"name":"CoreGPX"}],"navigatorTitle":[{"kind":"identifier","text":"parser:parseErrorOccurred:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/XMLParserDelegate-Implementations"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser/parser(_:parseErrorOccurred:)":{"role":"symbol","title":"parser(_:parseErrorOccurred:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"XMLParser","preciseIdentifier":"c:objc(cs)NSXMLParser"},{"kind":"text","text":", "},{"kind":"externalParam","text":"parseErrorOccurred"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Handling of XML parser’s thrown error. (if there is any)"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/parser(_:parseErrorOccurred:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parser:parseErrorOccurred:"}],"url":"\/documentation\/coregpx\/gpxparser\/parser(_:parseerroroccurred:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser/XMLParserDelegate-Implementations":{"role":"collectionGroup","title":"XMLParserDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/XMLParserDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/coregpx\/gpxparser\/xmlparserdelegate-implementations"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser":{"role":"symbol","title":"GPXParser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXParser"}],"abstract":[{"type":"text","text":"An event-driven parser (SAX parser), currently parses GPX v1.1 files only."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXParser"}],"url":"\/documentation\/coregpx\/gpxparser"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"parser:parseErrorOccurred:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parser:parseErrorOccurred:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"parser:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSXMLParser","preciseIdentifier":"c:objc(cs)NSXMLParser"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"parser"},{"kind":"text","text":" "},{"kind":"identifier","text":"parseErrorOccurred:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"parseError"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser~1parser(_:parseErrorOccurred:)\/title","value":"parser:parseErrorOccurred:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser~1parser(_:parseErrorOccurred:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parser:parseErrorOccurred:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser\/title","value":"GPXParser"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser\/fragments","value":[{"kind":"identifier","text":"GPXParser"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}