{"variants":[{"paths":["\/documentation\/coregpx\/gpxparser\/xmlparserdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/coregpx\/gpxparser\/xmlparserdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/XMLParserDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/parser(_:didEndElement:namespaceURI:qualifiedName:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/parser(_:foundCharacters:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/parser(_:parseErrorOccurred:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"CoreGPX"}],"role":"collectionGroup","title":"XMLParserDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser/parser(_:parseErrorOccurred:)":{"role":"symbol","title":"parser(_:parseErrorOccurred:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"XMLParser","preciseIdentifier":"c:objc(cs)NSXMLParser"},{"kind":"text","text":", "},{"kind":"externalParam","text":"parseErrorOccurred"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Handling of XML parser’s thrown error. (if there is any)"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/parser(_:parseErrorOccurred:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parser:parseErrorOccurred:"}],"url":"\/documentation\/coregpx\/gpxparser\/parser(_:parseerroroccurred:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser/parser(_:didEndElement:namespaceURI:qualifiedName:)":{"role":"symbol","title":"parser(_:didEndElement:namespaceURI:qualifiedName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"XMLParser","preciseIdentifier":"c:objc(cs)NSXMLParser"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEndElement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"namespaceURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"qualifiedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Default XML Parser Delegate’s end element ("},{"type":"text","text":") callback."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/parser(_:didEndElement:namespaceURI:qualifiedName:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parser:didEndElement:namespaceURI:qualifiedName:"}],"url":"\/documentation\/coregpx\/gpxparser\/parser(_:didendelement:namespaceuri:qualifiedname:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser/parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)":{"role":"symbol","title":"parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"XMLParser","preciseIdentifier":"c:objc(cs)NSXMLParser"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartElement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"namespaceURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"qualifiedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"attributes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Default XML Parser Delegate’s start element ("},{"type":"text","text":") callback."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parser:didStartElement:namespaceURI:qualifiedName:attributes:"}],"url":"\/documentation\/coregpx\/gpxparser\/parser(_:didstartelement:namespaceuri:qualifiedname:attributes:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser":{"role":"symbol","title":"GPXParser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXParser"}],"abstract":[{"type":"text","text":"An event-driven parser (SAX parser), currently parses GPX v1.1 files only."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXParser"}],"url":"\/documentation\/coregpx\/gpxparser"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser/parser(_:foundCharacters:)":{"role":"symbol","title":"parser(_:foundCharacters:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"XMLParser","preciseIdentifier":"c:objc(cs)NSXMLParser"},{"kind":"text","text":", "},{"kind":"externalParam","text":"foundCharacters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Default XML Parser Delegate callback when characters are found."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/parser(_:foundCharacters:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parser:foundCharacters:"}],"url":"\/documentation\/coregpx\/gpxparser\/parser(_:foundcharacters:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/parser(_:didEndElement:namespaceURI:qualifiedName:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/parser(_:foundCharacters:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/parser(_:parseErrorOccurred:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser~1parser(_:parseErrorOccurred:)\/title","value":"parser:parseErrorOccurred:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser~1parser(_:parseErrorOccurred:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parser:parseErrorOccurred:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser~1parser(_:didEndElement:namespaceURI:qualifiedName:)\/title","value":"parser:didEndElement:namespaceURI:qualifiedName:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser~1parser(_:didEndElement:namespaceURI:qualifiedName:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parser:didEndElement:namespaceURI:qualifiedName:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser~1parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)\/title","value":"parser:didStartElement:namespaceURI:qualifiedName:attributes:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser~1parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parser:didStartElement:namespaceURI:qualifiedName:attributes:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser\/title","value":"GPXParser"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser\/fragments","value":[{"kind":"identifier","text":"GPXParser"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser~1parser(_:foundCharacters:)\/title","value":"parser:foundCharacters:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser~1parser(_:foundCharacters:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parser:foundCharacters:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}