{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newTrackpointWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"longitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackPoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackPoint","text":"GPXTrackPoint"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxtracksegment\/newtrackpointwith(latitude:longitude:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/newTrackpointWith(latitude:longitude:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes a new trackpoint to segment, and returns the trackpoint."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newTrackpointWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"longitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GPXTrackPoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackPoint"}],"title":"newTrackpointWith(latitude:longitude:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:7CoreGPX15GPXTrackSegmentC17newTrackpointWith8latitude9longitudeAA0C5PointCSd_SdtF","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrackSegment":{"role":"symbol","title":"GPXTrackSegment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrackSegment"}],"abstract":[{"type":"text","text":"A track segment that holds data on all track points in the particular segment."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXTrackSegment"}],"url":"\/documentation\/coregpx\/gpxtracksegment"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrackSegment/newTrackpointWith(latitude:longitude:)":{"role":"symbol","title":"newTrackpointWith(latitude:longitude:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newTrackpointWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"longitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GPXTrackPoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackPoint"}],"abstract":[{"type":"text","text":"Initializes a new trackpoint to segment, and returns the trackpoint."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/newTrackpointWith(latitude:longitude:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtracksegment\/newtrackpointwith(latitude:longitude:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrackPoint":{"role":"symbol","title":"GPXTrackPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrackPoint"}],"abstract":[{"type":"text","text":"A track point is just like a waypoint or route point, but is suited to be part of a track segment."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackPoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXTrackPoint"}],"url":"\/documentation\/coregpx\/gpxtrackpoint"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackSegment\/title","value":"GPXTrackSegment"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackSegment\/fragments","value":[{"kind":"identifier","text":"GPXTrackSegment"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackPoint\/title","value":"GPXTrackPoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackPoint\/fragments","value":[{"kind":"identifier","text":"GPXTrackPoint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}