{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackpoints"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackPoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackPoint","text":"GPXTrackPoint"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxtracksegment\/trackpoints"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/trackpoints","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Track points stored in current segment."}],"kind":"symbol","metadata":{"role":"symbol","title":"trackpoints","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackpoints"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXTrackPoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackPoint"},{"kind":"text","text":"]"}],"symbolKind":"property","externalID":"s:7CoreGPX15GPXTrackSegmentC11trackpointsSayAA0C5PointCGvp","modules":[{"name":"CoreGPX"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrackSegment/trackpoints":{"role":"symbol","title":"trackpoints","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackpoints"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXTrackPoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackPoint"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Track points stored in current segment."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/trackpoints","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/coregpx\/gpxtracksegment\/trackpoints"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrackSegment":{"role":"symbol","title":"GPXTrackSegment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrackSegment"}],"abstract":[{"type":"text","text":"A track segment that holds data on all track points in the particular segment."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXTrackSegment"}],"url":"\/documentation\/coregpx\/gpxtracksegment"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrackPoint":{"role":"symbol","title":"GPXTrackPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrackPoint"}],"abstract":[{"type":"text","text":"A track point is just like a waypoint or route point, but is suited to be part of a track segment."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackPoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXTrackPoint"}],"url":"\/documentation\/coregpx\/gpxtrackpoint"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackSegment\/title","value":"GPXTrackSegment"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackSegment\/fragments","value":[{"kind":"identifier","text":"GPXTrackSegment"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackPoint\/title","value":"GPXTrackPoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackPoint\/fragments","value":[{"kind":"identifier","text":"GPXTrackPoint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}