{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"point"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXPoint","text":"GPXPoint"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxpointsegment\/remove(point:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPointSegment\/remove(point:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Remove a single point in the point segment"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"point"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXPoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXPoint"},{"kind":"text","text":")"}],"title":"remove(point:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:7CoreGPX15GPXPointSegmentC6remove5pointyAA0C0C_tF","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPointSegment"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXPointSegment":{"role":"symbol","title":"GPXPointSegment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXPointSegment"}],"abstract":[{"type":"text","text":"This class ("},{"type":"codeVoice","code":"ptsegType"},{"type":"text","text":") is added to conform with the GPX v1.1 schema."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPointSegment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXPointSegment"}],"url":"\/documentation\/coregpx\/gpxpointsegment"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXPoint":{"role":"symbol","title":"GPXPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXPoint"}],"abstract":[{"type":"text","text":"This class ("},{"type":"codeVoice","code":"ptType"},{"type":"text","text":") is added to conform with the GPX v1.1 schema."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXPoint"}],"url":"\/documentation\/coregpx\/gpxpoint"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXPointSegment/remove(point:)":{"role":"symbol","title":"remove(point:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"point"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXPoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXPoint"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Remove a single point in the point segment"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPointSegment\/remove(point:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxpointsegment\/remove(point:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPointSegment\/title","value":"GPXPointSegment"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPointSegment\/fragments","value":[{"kind":"identifier","text":"GPXPointSegment"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPoint\/title","value":"GPXPoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPoint\/fragments","value":[{"kind":"identifier","text":"GPXPoint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}