{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canDraw"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mapRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKMapRect","preciseIdentifier":"c:@SA@MKMapRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"zoomScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKZoomScale","preciseIdentifier":"c:@T@MKZoomScale"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapcache\/cachedtileoverlayrenderer\/candraw(_:zoomscale:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapcache\/cachedtileoverlayrenderer\/candraw(_:zoomscale:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer\/canDraw(_:zoomScale:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicates if the renderer is ready to draw. It´s always true"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canDraw"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapRect","preciseIdentifier":"c:@SA@MKMapRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"zoomScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKZoomScale","preciseIdentifier":"c:@T@MKZoomScale"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"canDraw(_:zoomScale:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@MapCache@objc(cs)CachedTileOverlayRenderer(im)canDrawMapRect:zoomScale:","modules":[{"name":"MapCache"}],"navigatorTitle":[{"kind":"identifier","text":"canDrawMapRect:zoomScale:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer"]]},"references":{"doc://org.cocoapods.MapCache/documentation/MapCache/CachedTileOverlayRenderer/canDraw(_:zoomScale:)":{"role":"symbol","title":"canDraw(_:zoomScale:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canDraw"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapRect","preciseIdentifier":"c:@SA@MKMapRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"zoomScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKZoomScale","preciseIdentifier":"c:@T@MKZoomScale"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Indicates if the renderer is ready to draw. It´s always true"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer\/canDraw(_:zoomScale:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canDrawMapRect:zoomScale:"}],"url":"\/documentation\/mapcache\/cachedtileoverlayrenderer\/candraw(_:zoomscale:)"},"doc://org.cocoapods.MapCache/documentation/MapCache":{"role":"collection","title":"MapCache","abstract":[],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache","kind":"symbol","type":"topic","url":"\/documentation\/mapcache"},"doc://org.cocoapods.MapCache/documentation/MapCache/CachedTileOverlayRenderer":{"role":"symbol","title":"CachedTileOverlayRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CachedTileOverlayRenderer"}],"abstract":[{"type":"text","text":"A Tile overlay that supports to zoom beyond the maximumZ"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CachedTileOverlayRenderer"}],"url":"\/documentation\/mapcache\/cachedtileoverlayrenderer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"canDrawMapRect:zoomScale:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canDrawMapRect:zoomScale:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"canDrawMapRect:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapRect","preciseIdentifier":"c:@SA@MKMapRect"},{"kind":"text","text":")"},{"kind":"internalParam","text":"mapRect"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoomScale:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKZoomScale","preciseIdentifier":"c:@T@MKZoomScale"},{"kind":"text","text":")"},{"kind":"internalParam","text":"zoomScale"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlayRenderer~1canDraw(_:zoomScale:)\/title","value":"canDrawMapRect:zoomScale:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlayRenderer~1canDraw(_:zoomScale:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canDrawMapRect:zoomScale:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlayRenderer\/title","value":"CachedTileOverlayRenderer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlayRenderer\/fragments","value":[{"kind":"identifier","text":"CachedTileOverlayRenderer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}