{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"draw"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mapRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKMapRect","preciseIdentifier":"c:@SA@MKMapRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"zoomScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKZoomScale","preciseIdentifier":"c:@T@MKZoomScale"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":" "},{"kind":"internalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGContext","preciseIdentifier":"c:@T@CGContextRef"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"mapRect","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the map rect where the tiles need to be drawn"}]}]},{"name":"zoomScale","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"current zoom in the map"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapcache\/cachedtileoverlayrenderer\/draw(_:zoomscale:in:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapcache\/cachedtileoverlayrenderer\/draw(_:zoomscale:in:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer\/draw(_:zoomScale:in:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Draws the tile in the map"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"draw"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapRect","preciseIdentifier":"c:@SA@MKMapRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"zoomScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKZoomScale","preciseIdentifier":"c:@T@MKZoomScale"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGContext","preciseIdentifier":"c:@T@CGContextRef"},{"kind":"text","text":")"}],"title":"draw(_:zoomScale:in:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@MapCache@objc(cs)CachedTileOverlayRenderer(im)drawMapRect:zoomScale:inContext:","modules":[{"name":"MapCache"}],"navigatorTitle":[{"kind":"identifier","text":"drawMapRect:zoomScale:inContext:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer"]]},"references":{"doc://org.cocoapods.MapCache/documentation/MapCache/CachedTileOverlayRenderer":{"role":"symbol","title":"CachedTileOverlayRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CachedTileOverlayRenderer"}],"abstract":[{"type":"text","text":"A Tile overlay that supports to zoom beyond the maximumZ"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CachedTileOverlayRenderer"}],"url":"\/documentation\/mapcache\/cachedtileoverlayrenderer"},"doc://org.cocoapods.MapCache/documentation/MapCache":{"role":"collection","title":"MapCache","abstract":[],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache","kind":"symbol","type":"topic","url":"\/documentation\/mapcache"},"doc://org.cocoapods.MapCache/documentation/MapCache/CachedTileOverlayRenderer/draw(_:zoomScale:in:)":{"role":"symbol","title":"draw(_:zoomScale:in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"draw"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapRect","preciseIdentifier":"c:@SA@MKMapRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"zoomScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKZoomScale","preciseIdentifier":"c:@T@MKZoomScale"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGContext","preciseIdentifier":"c:@T@CGContextRef"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Draws the tile in the map"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer\/draw(_:zoomScale:in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"drawMapRect:zoomScale:inContext:"}],"url":"\/documentation\/mapcache\/cachedtileoverlayrenderer\/draw(_:zoomscale:in:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"drawMapRect:zoomScale:inContext:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"drawMapRect:zoomScale:inContext:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"drawMapRect:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapRect","preciseIdentifier":"c:@SA@MKMapRect"},{"kind":"text","text":")"},{"kind":"internalParam","text":"mapRect"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoomScale:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKZoomScale","preciseIdentifier":"c:@T@MKZoomScale"},{"kind":"text","text":")"},{"kind":"internalParam","text":"zoomScale"},{"kind":"text","text":" "},{"kind":"identifier","text":"inContext:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"CGContext","preciseIdentifier":"c:@S@CGContext"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"context"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlayRenderer\/title","value":"CachedTileOverlayRenderer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlayRenderer\/fragments","value":[{"kind":"identifier","text":"CachedTileOverlayRenderer"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlayRenderer~1draw(_:zoomScale:in:)\/title","value":"drawMapRect:zoomScale:inContext:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlayRenderer~1draw(_:zoomScale:in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"drawMapRect:zoomScale:inContext:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}