{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CachedTileOverlay"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapcache\/cachedtileoverlay"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapcache\/cachedtileoverlay"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.MapCache\/objc(cs)MKTileOverlay"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.MapCache\/objc(pl)MKAnnotation","doc:\/\/org.cocoapods.MapCache\/objc(pl)MKOverlay","doc:\/\/org.cocoapods.MapCache\/objc(pl)NSObject","doc:\/\/org.cocoapods.MapCache\/s7CVarArgP","doc:\/\/org.cocoapods.MapCache\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.MapCache\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.MapCache\/SQ","doc:\/\/org.cocoapods.MapCache\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Whenever a tile is requested by the "},{"type":"codeVoice","code":"MapView"},{"type":"text","text":", it calls the "},{"type":"codeVoice","code":"MKTileOverlay.loadTile"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This class overrides the default "},{"type":"codeVoice","code":"MKTileOverlay"},{"type":"text","text":"to provide support to "},{"type":"codeVoice","code":"MapCache"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CachedTileOverlay"}],"title":"CachedTileOverlay","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@MapCache@objc(cs)CachedTileOverlay","modules":[{"name":"MapCache"}],"navigatorTitle":[{"kind":"identifier","text":"CachedTileOverlay"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay\/init(withCache:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay\/useCache"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay\/loadTile(at:result:)","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay\/url(forTilePath:)"]}],"references":{"doc://org.cocoapods.MapCache/documentation/MapCache/CachedTileOverlay":{"role":"symbol","title":"CachedTileOverlay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CachedTileOverlay"}],"abstract":[{"type":"text","text":"Whenever a tile is requested by the "},{"type":"codeVoice","code":"MapView"},{"type":"text","text":", it calls the "},{"type":"codeVoice","code":"MKTileOverlay.loadTile"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This class overrides the default "},{"type":"codeVoice","code":"MKTileOverlay"},{"type":"text","text":"to provide support to "},{"type":"codeVoice","code":"MapCache"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CachedTileOverlay"}],"url":"\/documentation\/mapcache\/cachedtileoverlay"},"doc://org.cocoapods.MapCache/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.MapCache\/SH"},"doc://org.cocoapods.MapCache/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.MapCache\/s7CVarArgP"},"doc://org.cocoapods.MapCache/documentation/MapCache/CachedTileOverlay/url(forTilePath:)":{"role":"symbol","title":"url(forTilePath:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forTilePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKTileOverlayPath","preciseIdentifier":"c:@SA@MKTileOverlayPath"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}],"abstract":[{"type":"text","text":"Generates the URL for the tile to be requested."},{"type":"text","text":" "},{"type":"text","text":"It replaces the values of {z},{x} and {y} in the "},{"type":"codeVoice","code":"urlTemplate"},{"type":"text","text":"defined in "},{"type":"codeVoice","code":"mapCache.config"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay\/url(forTilePath:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"URLForTilePath:"}],"url":"\/documentation\/mapcache\/cachedtileoverlay\/url(fortilepath:)"},"doc://org.cocoapods.MapCache/documentation/MapCache/CachedTileOverlay/useCache":{"role":"symbol","title":"useCache","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"useCache"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"If true "},{"type":"codeVoice","code":"loadTile"},{"type":"text","text":" uses the implementation of  the "},{"type":"codeVoice","code":"mapCache"},{"type":"text","text":" var. If "},{"type":"codeVoice","code":"false"},{"type":"text","text":", uses the"},{"type":"text","text":" "},{"type":"text","text":"default "},{"type":"codeVoice","code":"MKTileOverlay"},{"type":"text","text":"implementation from Apple."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay\/useCache","kind":"symbol","type":"topic","url":"\/documentation\/mapcache\/cachedtileoverlay\/usecache"},"doc://org.cocoapods.MapCache/documentation/MapCache/CachedTileOverlay/loadTile(at:result:)":{"role":"symbol","title":"loadTile(at:result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadTile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKTileOverlayPath","preciseIdentifier":"c:@SA@MKTileOverlayPath"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When invoked it will load the tile using the standard OS implementation (if "},{"type":"codeVoice","code":"useCache"},{"type":"text","text":"is "},{"type":"codeVoice","code":"false"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"or from the cache (if "},{"type":"codeVoice","code":"useCache"},{"type":"text","text":" is "},{"type":"codeVoice","code":"true"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay\/loadTile(at:result:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadTileAtPath:result:"}],"url":"\/documentation\/mapcache\/cachedtileoverlay\/loadtile(at:result:)"},"doc://org.cocoapods.MapCache/documentation/MapCache":{"role":"collection","title":"MapCache","abstract":[],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache","kind":"symbol","type":"topic","url":"\/documentation\/mapcache"},"doc://org.cocoapods.MapCache/objc(pl)MKOverlay":{"type":"unresolvable","title":"MapKit.MKOverlay","identifier":"doc:\/\/org.cocoapods.MapCache\/objc(pl)MKOverlay"},"doc://org.cocoapods.MapCache/documentation/MapCache/CachedTileOverlay/init(withCache:)":{"role":"symbol","title":"init(withCache:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCache"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MapCacheProtocol","preciseIdentifier":"s:8MapCache0aB8ProtocolP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Constructor."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay\/init(withCache:)","kind":"symbol","type":"topic","url":"\/documentation\/mapcache\/cachedtileoverlay\/init(withcache:)"},"doc://org.cocoapods.MapCache/objc(pl)MKAnnotation":{"type":"unresolvable","title":"MapKit.MKAnnotation","identifier":"doc:\/\/org.cocoapods.MapCache\/objc(pl)MKAnnotation"},"doc://org.cocoapods.MapCache/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.MapCache\/SQ"},"doc://org.cocoapods.MapCache/objc(cs)MKTileOverlay":{"type":"unresolvable","title":"MKTileOverlay","identifier":"doc:\/\/org.cocoapods.MapCache\/objc(cs)MKTileOverlay"},"doc://org.cocoapods.MapCache/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.MapCache\/s23CustomStringConvertibleP"},"doc://org.cocoapods.MapCache/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.MapCache\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.MapCache/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.MapCache\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CachedTileOverlay"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CachedTileOverlay"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CachedTileOverlay"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay\/loadTile(at:result:)","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay\/url(forTilePath:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.MapCache\/objc(cs)MKTileOverlay"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CachedTileOverlay"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"MKTileOverlay","preciseIdentifier":"c:objc(cs)MKTileOverlay"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlay\/title","value":"CachedTileOverlay"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlay\/fragments","value":[{"kind":"identifier","text":"CachedTileOverlay"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlay~1url(forTilePath:)\/title","value":"URLForTilePath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlay~1url(forTilePath:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"URLForTilePath:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlay~1loadTile(at:result:)\/title","value":"loadTileAtPath:result:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlay~1loadTile(at:result:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadTileAtPath:result:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}