{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CachedTileOverlayRenderer"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Tile servers allow from 1 to a certain zoom level typically between 16 and 21 (set in "},{"type":"codeVoice","code":"MapCacheConfig.maximumZ"},{"type":"text","text":")."},{"type":"text","text":" "},{"type":"text","text":"Beyond that zoom levels tiles are not available in the server"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This renderer takes the maximumZ tile and extracts the portion that would correspond to the requested level."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapcache\/cachedtileoverlayrenderer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapcache\/cachedtileoverlayrenderer"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.MapCache\/objc(cs)MKTileOverlayRenderer"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.MapCache\/objc(pl)NSObject","doc:\/\/org.cocoapods.MapCache\/s7CVarArgP","doc:\/\/org.cocoapods.MapCache\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.MapCache\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.MapCache\/SQ","doc:\/\/org.cocoapods.MapCache\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A Tile overlay that supports to zoom beyond the maximumZ"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CachedTileOverlayRenderer"}],"title":"CachedTileOverlayRenderer","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@MapCache@objc(cs)CachedTileOverlayRenderer","modules":[{"name":"MapCache"}],"navigatorTitle":[{"kind":"identifier","text":"CachedTileOverlayRenderer"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer\/canDraw(_:zoomScale:)","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer\/draw(_:zoomScale:in:)"]}],"references":{"doc://org.cocoapods.MapCache/documentation/MapCache/CachedTileOverlayRenderer/initWithTileOverlay:":{"role":"symbol","title":"initWithTileOverlay:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTileOverlay:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer\/initWithTileOverlay:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithTileOverlay:"}],"url":"\/documentation\/mapcache\/cachedtileoverlayrenderer\/initwithtileoverlay:"},"doc://org.cocoapods.MapCache/documentation/MapCache/CachedTileOverlayRenderer/initWithOverlay:":{"role":"symbol","title":"initWithOverlay:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOverlay:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer\/initWithOverlay:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithOverlay:"}],"url":"\/documentation\/mapcache\/cachedtileoverlayrenderer\/initwithoverlay:"},"doc://org.cocoapods.MapCache/documentation/MapCache":{"role":"collection","title":"MapCache","abstract":[],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache","kind":"symbol","type":"topic","url":"\/documentation\/mapcache"},"doc://org.cocoapods.MapCache/documentation/MapCache/CachedTileOverlayRenderer/draw(_:zoomScale:in:)":{"role":"symbol","title":"draw(_:zoomScale:in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"draw"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapRect","preciseIdentifier":"c:@SA@MKMapRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"zoomScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKZoomScale","preciseIdentifier":"c:@T@MKZoomScale"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGContext","preciseIdentifier":"c:@T@CGContextRef"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Draws the tile in the map"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer\/draw(_:zoomScale:in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"drawMapRect:zoomScale:inContext:"}],"url":"\/documentation\/mapcache\/cachedtileoverlayrenderer\/draw(_:zoomscale:in:)"},"doc://org.cocoapods.MapCache/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.MapCache\/objc(pl)NSObject"},"doc://org.cocoapods.MapCache/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.MapCache\/SQ"},"doc://org.cocoapods.MapCache/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.MapCache\/s23CustomStringConvertibleP"},"doc://org.cocoapods.MapCache/documentation/MapCache/CachedTileOverlayRenderer/canDraw(_:zoomScale:)":{"role":"symbol","title":"canDraw(_:zoomScale:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canDraw"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapRect","preciseIdentifier":"c:@SA@MKMapRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"zoomScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKZoomScale","preciseIdentifier":"c:@T@MKZoomScale"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Indicates if the renderer is ready to draw. It´s always true"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer\/canDraw(_:zoomScale:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canDrawMapRect:zoomScale:"}],"url":"\/documentation\/mapcache\/cachedtileoverlayrenderer\/candraw(_:zoomscale:)"},"doc://org.cocoapods.MapCache/documentation/MapCache/CachedTileOverlayRenderer":{"role":"symbol","title":"CachedTileOverlayRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CachedTileOverlayRenderer"}],"abstract":[{"type":"text","text":"A Tile overlay that supports to zoom beyond the maximumZ"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CachedTileOverlayRenderer"}],"url":"\/documentation\/mapcache\/cachedtileoverlayrenderer"},"doc://org.cocoapods.MapCache/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.MapCache\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.MapCache/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.MapCache\/SH"},"doc://org.cocoapods.MapCache/objc(cs)MKTileOverlayRenderer":{"type":"unresolvable","title":"MKTileOverlayRenderer","identifier":"doc:\/\/org.cocoapods.MapCache\/objc(cs)MKTileOverlayRenderer"},"doc://org.cocoapods.MapCache/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.MapCache\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CachedTileOverlayRenderer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CachedTileOverlayRenderer"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CachedTileOverlayRenderer"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer\/canDraw(_:zoomScale:)","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer\/draw(_:zoomScale:in:)","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer\/initWithOverlay:","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer\/initWithTileOverlay:"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.MapCache\/objc(cs)MKTileOverlayRenderer"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CachedTileOverlayRenderer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"MKTileOverlayRenderer","preciseIdentifier":"c:objc(cs)MKTileOverlayRenderer"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlayRenderer~1draw(_:zoomScale:in:)\/title","value":"drawMapRect:zoomScale:inContext:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlayRenderer~1draw(_:zoomScale:in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"drawMapRect:zoomScale:inContext:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlayRenderer~1canDraw(_:zoomScale:)\/title","value":"canDrawMapRect:zoomScale:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlayRenderer~1canDraw(_:zoomScale:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canDrawMapRect:zoomScale:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlayRenderer\/title","value":"CachedTileOverlayRenderer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlayRenderer\/fragments","value":[{"kind":"identifier","text":"CachedTileOverlayRenderer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}