{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegionDownloaderDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapcache\/regiondownloaderdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapcache\/regiondownloaderdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloaderDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Delegate protocol of "},{"type":"codeVoice","code":"RegionDownloader"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Implement this protocol whenever  you use "},{"type":"codeVoice","code":"RegionDownloader"},{"type":"text","text":" it drovides feedback while donwloading a"},{"type":"text","text":" "},{"type":"text","text":"region (f.i, downloaded %) and callsback the delegate once the download finished."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegionDownloaderDelegate"}],"title":"RegionDownloaderDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@MapCache@objc(pl)RegionDownloaderDelegate","modules":[{"name":"MapCache"}],"navigatorTitle":[{"kind":"identifier","text":"RegionDownloaderDelegate"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloaderDelegate\/regionDownloader(_:didDownloadPercentage:)","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloaderDelegate\/regionDownloader(_:didFinishDownload:)"]}],"references":{"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloaderDelegate/regionDownloader(_:didFinishDownload:)":{"navigatorTitle":[{"kind":"identifier","text":"regionDownloader:didFinishDownload:"}],"role":"symbol","title":"regionDownloader(_:didFinishDownload:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"regionDownloader"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RegionDownloader","preciseIdentifier":"c:@M@MapCache@objc(cs)RegionDownloader"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishDownload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TileNumber","preciseIdentifier":"s:8MapCache10TileNumbera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Did Finish Download all tiles."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloaderDelegate\/regionDownloader(_:didFinishDownload:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapcache\/regiondownloaderdelegate\/regiondownloader(_:didfinishdownload:)"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloaderDelegate":{"role":"symbol","title":"RegionDownloaderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegionDownloaderDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol of "},{"type":"codeVoice","code":"RegionDownloader"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Implement this protocol whenever  you use "},{"type":"codeVoice","code":"RegionDownloader"},{"type":"text","text":" it drovides feedback while donwloading a"},{"type":"text","text":" "},{"type":"text","text":"region (f.i, downloaded %) and callsback the delegate once the download finished."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloaderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RegionDownloaderDelegate"}],"url":"\/documentation\/mapcache\/regiondownloaderdelegate"},"doc://org.cocoapods.MapCache/documentation/MapCache":{"role":"collection","title":"MapCache","abstract":[],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache","kind":"symbol","type":"topic","url":"\/documentation\/mapcache"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloaderDelegate/regionDownloader(_:didDownloadPercentage:)":{"navigatorTitle":[{"kind":"identifier","text":"regionDownloader:didDownloadPercentage:"}],"role":"symbol","title":"regionDownloader(_:didDownloadPercentage:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"regionDownloader"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RegionDownloader","preciseIdentifier":"c:@M@MapCache@objc(cs)RegionDownloader"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDownloadPercentage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Did download the percentage."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloaderDelegate\/regionDownloader(_:didDownloadPercentage:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapcache\/regiondownloaderdelegate\/regiondownloader(_:diddownloadpercentage:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"RegionDownloaderDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"RegionDownloaderDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"RegionDownloaderDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloaderDelegate\/regionDownloader(_:didDownloadPercentage:)","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloaderDelegate\/regionDownloader(_:didFinishDownload:)"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegionDownloaderDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloaderDelegate~1regionDownloader(_:didFinishDownload:)\/title","value":"regionDownloader:didFinishDownload:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloaderDelegate~1regionDownloader(_:didFinishDownload:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"regionDownloader:didFinishDownload:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloaderDelegate\/title","value":"RegionDownloaderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloaderDelegate\/fragments","value":[{"kind":"identifier","text":"RegionDownloaderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloaderDelegate~1regionDownloader(_:didDownloadPercentage:)\/title","value":"regionDownloader:didDownloadPercentage:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloaderDelegate~1regionDownloader(_:didDownloadPercentage:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"regionDownloader:didDownloadPercentage:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}