{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegionDownloader"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This class allows you to download all the tiles of a region of the map."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Internally what it does is to iterate over every tile coordinate within the region and  request to a"},{"type":"text","text":" "},{"type":"text","text":"mapCache to download it by calling its "},{"type":"codeVoice","code":"loadTile"},{"type":"text","text":" method."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In order to keep track of the downloaded data you can implement "},{"type":"codeVoice","code":"ReguionDownloaderDelegate"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Based on the value of "},{"type":"codeVoice","code":"incrementInPercentageNotification"},{"type":"text","text":" the delegate will be called."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Experimental"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapcache\/regiondownloader"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapcache\/regiondownloader"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.MapCache\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.MapCache\/objc(pl)NSObject","doc:\/\/org.cocoapods.MapCache\/s7CVarArgP","doc:\/\/org.cocoapods.MapCache\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.MapCache\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.MapCache\/SQ","doc:\/\/org.cocoapods.MapCache\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Hey! I need to download this area of the map."},{"type":"text","text":" "},{"type":"text","text":"No problemo."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegionDownloader"}],"title":"RegionDownloader","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@MapCache@objc(cs)RegionDownloader","modules":[{"name":"MapCache"}],"navigatorTitle":[{"kind":"identifier","text":"RegionDownloader"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/init(forRegion:mapCache:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/averageTileSizeBytes","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/delegate","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/downloadedBytes","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/downloadedPercentage","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/downloadedTiles","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/failedTileDownloads","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/incrementInPercentageNotification","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/mapCache","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/nextPercentageToNotify","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/pendingTilesToDownload","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/region","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/successfulTileDownloads","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/totalTilesToDownload"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/estimateRegionByteSize()","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/resetCounters()","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/start()"]}],"references":{"doc://org.cocoapods.MapCache/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.MapCache\/objc(cs)NSObject"},"doc://org.cocoapods.MapCache/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.MapCache\/s23CustomStringConvertibleP"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader/pendingTilesToDownload":{"role":"symbol","title":"pendingTilesToDownload","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pendingTilesToDownload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TileNumber","preciseIdentifier":"s:8MapCache10TileNumbera"}],"abstract":[{"type":"text","text":"Number of tiles pending to be downloaded."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/pendingTilesToDownload","kind":"symbol","type":"topic","url":"\/documentation\/mapcache\/regiondownloader\/pendingtilestodownload"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader/successfulTileDownloads":{"role":"symbol","title":"successfulTileDownloads","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"successfulTileDownloads"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TileNumber","preciseIdentifier":"s:8MapCache10TileNumbera"}],"abstract":[{"type":"text","text":"Keeps the number of tiles already downloaded."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/successfulTileDownloads","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"successfulTileDownloads"}],"url":"\/documentation\/mapcache\/regiondownloader\/successfultiledownloads"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader":{"role":"symbol","title":"RegionDownloader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegionDownloader"}],"abstract":[{"type":"text","text":"Hey! I need to download this area of the map."},{"type":"text","text":" "},{"type":"text","text":"No problemo."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RegionDownloader"}],"url":"\/documentation\/mapcache\/regiondownloader"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader/nextPercentageToNotify":{"role":"symbol","title":"nextPercentageToNotify","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextPercentageToNotify"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Percentage to notify thought delegate."},{"type":"text","text":" "},{"type":"text","text":"If set to >100 will only notify on finish download."},{"type":"text","text":" "},{"type":"text","text":"If set to a percentage  smaller than "},{"type":"codeVoice","code":"downloadedPercentage"},{"type":"text","text":", it will never notify."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/nextPercentageToNotify","kind":"symbol","type":"topic","url":"\/documentation\/mapcache\/regiondownloader\/nextpercentagetonotify"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader/averageTileSizeBytes":{"role":"symbol","title":"averageTileSizeBytes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"averageTileSizeBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"abstract":[{"type":"text","text":"Returns the average"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/averageTileSizeBytes","kind":"symbol","type":"topic","url":"\/documentation\/mapcache\/regiondownloader\/averagetilesizebytes"},"doc://org.cocoapods.MapCache/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.MapCache\/SH"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader/downloadedBytes":{"role":"symbol","title":"downloadedBytes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadedBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"abstract":[{"type":"text","text":"Total number of downloaded data bytes."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/downloadedBytes","kind":"symbol","type":"topic","url":"\/documentation\/mapcache\/regiondownloader\/downloadedbytes"},"doc://org.cocoapods.MapCache/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.MapCache\/s7CVarArgP"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader/region":{"role":"symbol","title":"region","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"region"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TileCoordsRegion","preciseIdentifier":"s:8MapCache16TileCoordsRegionC"}],"abstract":[{"type":"text","text":"Region that will be downloaded."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/region","kind":"symbol","type":"topic","url":"\/documentation\/mapcache\/regiondownloader\/region"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RegionDownloaderDelegate","preciseIdentifier":"c:@M@MapCache@objc(pl)RegionDownloaderDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Delegate."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/mapcache\/regiondownloader\/delegate"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader/totalTilesToDownload":{"role":"symbol","title":"totalTilesToDownload","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalTilesToDownload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TileNumber","preciseIdentifier":"s:8MapCache10TileNumbera"}],"abstract":[{"type":"text","text":"Total number of tiles to be downloaded."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/totalTilesToDownload","kind":"symbol","type":"topic","url":"\/documentation\/mapcache\/regiondownloader\/totaltilestodownload"},"doc://org.cocoapods.MapCache/documentation/MapCache":{"role":"collection","title":"MapCache","abstract":[],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache","kind":"symbol","type":"topic","url":"\/documentation\/mapcache"},"doc://org.cocoapods.MapCache/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.MapCache\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader/estimateRegionByteSize()":{"role":"symbol","title":"estimateRegionByteSize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"estimateRegionByteSize"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"abstract":[{"type":"text","text":"Returns an estimation of the total number of bytes the whole region may occupy."},{"type":"text","text":" "},{"type":"text","text":"Again, it is an estimation."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/estimateRegionByteSize()","kind":"symbol","type":"topic","url":"\/documentation\/mapcache\/regiondownloader\/estimateregionbytesize()"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader/downloadedTiles":{"role":"symbol","title":"downloadedTiles","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadedTiles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TileNumber","preciseIdentifier":"s:8MapCache10TileNumbera"}],"abstract":[{"type":"text","text":"Keeps the number of tiles already downloaded successfully or failed."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/downloadedTiles","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"downloadedTiles"}],"url":"\/documentation\/mapcache\/regiondownloader\/downloadedtiles"},"doc://org.cocoapods.MapCache/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.MapCache\/objc(pl)NSObject"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader/incrementInPercentageNotification":{"role":"symbol","title":"incrementInPercentageNotification","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"incrementInPercentageNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The downloader will notify the delegate every time this."},{"type":"text","text":" "},{"type":"text","text":"For example if you set this to 5, it will notify when 5%, 10%, 15%, etc."},{"type":"text","text":" "},{"type":"text","text":"Default value 5."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/incrementInPercentageNotification","kind":"symbol","type":"topic","url":"\/documentation\/mapcache\/regiondownloader\/incrementinpercentagenotification"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader/start()":{"role":"symbol","title":"start()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Starts download."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/start()","kind":"symbol","type":"topic","url":"\/documentation\/mapcache\/regiondownloader\/start()"},"doc://org.cocoapods.MapCache/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.MapCache\/SQ"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader/init(forRegion:mapCache:)":{"role":"symbol","title":"init(forRegion:mapCache:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forRegion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TileCoordsRegion","preciseIdentifier":"s:8MapCache16TileCoordsRegionC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mapCache"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MapCacheProtocol","preciseIdentifier":"s:8MapCache0aB8ProtocolP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes the downloader with the region and the MapCache."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/init(forRegion:mapCache:)","kind":"symbol","type":"topic","url":"\/documentation\/mapcache\/regiondownloader\/init(forregion:mapcache:)"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader/mapCache":{"role":"symbol","title":"mapCache","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapCache"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MapCacheProtocol","preciseIdentifier":"s:8MapCache0aB8ProtocolP"}],"abstract":[{"type":"text","text":"Cache that is going to be used for saving\/loading the files."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/mapCache","kind":"symbol","type":"topic","url":"\/documentation\/mapcache\/regiondownloader\/mapcache"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader/downloadedPercentage":{"role":"symbol","title":"downloadedPercentage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadedPercentage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Percentage of tiles pending to download."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/downloadedPercentage","kind":"symbol","type":"topic","url":"\/documentation\/mapcache\/regiondownloader\/downloadedpercentage"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader/failedTileDownloads":{"role":"symbol","title":"failedTileDownloads","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedTileDownloads"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TileNumber","preciseIdentifier":"s:8MapCache10TileNumbera"}],"abstract":[{"type":"text","text":"Number of tiles to be downloaded"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/failedTileDownloads","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"failedTileDownloads"}],"url":"\/documentation\/mapcache\/regiondownloader\/failedtiledownloads"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader/resetCounters()":{"role":"symbol","title":"resetCounters()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetCounters"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Resets downloader counters."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/resetCounters()","kind":"symbol","type":"topic","url":"\/documentation\/mapcache\/regiondownloader\/resetcounters()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"RegionDownloader"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"RegionDownloader"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"RegionDownloader"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/downloadedTiles","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/failedTileDownloads","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/successfulTileDownloads"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.MapCache\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegionDownloader"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloader~1successfulTileDownloads\/title","value":"successfulTileDownloads"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloader~1successfulTileDownloads\/fragments","value":[{"kind":"identifier","text":"successfulTileDownloads"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloader\/title","value":"RegionDownloader"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloader\/fragments","value":[{"kind":"identifier","text":"RegionDownloader"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloader~1downloadedTiles\/title","value":"downloadedTiles"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloader~1downloadedTiles\/fragments","value":[{"kind":"identifier","text":"downloadedTiles"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloader~1failedTileDownloads\/title","value":"failedTileDownloads"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloader~1failedTileDownloads\/fragments","value":[{"kind":"identifier","text":"failedTileDownloads"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}