{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bounds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXBounds","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXBounds","text":"GPXBounds"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxmetadata\/bounds"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXMetadata\/bounds","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Boundaries of coordinates of the GPX file."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bounds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXBounds","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXBounds"},{"kind":"text","text":"?"}],"title":"bounds","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7CoreGPX11GPXMetadataC6boundsAA9GPXBoundsCSgvp","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXMetadata"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXMetadata":{"role":"symbol","title":"GPXMetadata","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXMetadata"}],"abstract":[{"type":"text","text":"A value type that represents the metadata header of a GPX file."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXMetadata"}],"url":"\/documentation\/coregpx\/gpxmetadata"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXBounds":{"role":"symbol","title":"GPXBounds","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXBounds"}],"abstract":[{"type":"text","text":"A value type that represents bounds based off GPX v1.1 schema’s "},{"type":"codeVoice","code":"boundsType"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXBounds","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXBounds"}],"url":"\/documentation\/coregpx\/gpxbounds"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXMetadata/bounds":{"role":"symbol","title":"bounds","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bounds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXBounds","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXBounds"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Boundaries of coordinates of the GPX file."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXMetadata\/bounds","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxmetadata\/bounds"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXMetadata\/title","value":"GPXMetadata"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXMetadata\/fragments","value":[{"kind":"identifier","text":"GPXMetadata"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXBounds\/title","value":"GPXBounds"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXBounds\/fragments","value":[{"kind":"identifier","text":"GPXBounds"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}