{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"copyright"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXCopyright","text":"GPXCopyright"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxmetadata\/copyright"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXMetadata\/copyright","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Copyright of the file, if required."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"copyright"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXCopyright","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXCopyright"},{"kind":"text","text":"?"}],"title":"copyright","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7CoreGPX11GPXMetadataC9copyrightAA12GPXCopyrightCSgvp","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXMetadata"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXCopyright":{"role":"symbol","title":"GPXCopyright","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXCopyright"}],"abstract":[{"type":"text","text":"A value type for representing copyright info"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXCopyright"}],"url":"\/documentation\/coregpx\/gpxcopyright"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXMetadata/copyright":{"role":"symbol","title":"copyright","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"copyright"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXCopyright","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXCopyright"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Copyright of the file, if required."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXMetadata\/copyright","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxmetadata\/copyright"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXMetadata":{"role":"symbol","title":"GPXMetadata","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXMetadata"}],"abstract":[{"type":"text","text":"A value type that represents the metadata header of a GPX file."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXMetadata"}],"url":"\/documentation\/coregpx\/gpxmetadata"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXCopyright\/title","value":"GPXCopyright"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXCopyright\/fragments","value":[{"kind":"identifier","text":"GPXCopyright"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXMetadata\/title","value":"GPXMetadata"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXMetadata\/fragments","value":[{"kind":"identifier","text":"GPXMetadata"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}