{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"link"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLink","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLink","text":"GPXLink"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxmetadata\/link"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXMetadata\/link","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A web link, usually one with information regarding the GPX file."}],"kind":"symbol","metadata":{"role":"symbol","title":"link","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"link"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXLink","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLink"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"s:7CoreGPX11GPXMetadataC4linkAA7GPXLinkCSgvp","modules":[{"name":"CoreGPX"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXMetadata"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"CoreGPX now support multiple links."}]}],"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLink":{"role":"symbol","title":"GPXLink","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLink"}],"abstract":[{"type":"text","text":"A value type that can hold a web link to a external resource, or external information about a certain attribute."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLink","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLink"}],"url":"\/documentation\/coregpx\/gpxlink"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXMetadata/link":{"role":"symbol","title":"link","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"link"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXLink","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLink"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A web link, usually one with information regarding the GPX file."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXMetadata\/link","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/coregpx\/gpxmetadata\/link"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXMetadata":{"role":"symbol","title":"GPXMetadata","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXMetadata"}],"abstract":[{"type":"text","text":"A value type that represents the metadata header of a GPX file."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXMetadata"}],"url":"\/documentation\/coregpx\/gpxmetadata"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLink\/title","value":"GPXLink"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLink\/fragments","value":[{"kind":"identifier","text":"GPXLink"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXMetadata\/title","value":"GPXMetadata"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXMetadata\/fragments","value":[{"kind":"identifier","text":"GPXMetadata"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}