{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"segments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrackSegment","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLegacyTrackSegment","text":"GPXLegacyTrackSegment"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxlegacytrack\/segments"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrack\/segments","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"segments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXLegacyTrackSegment","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLegacyTrackSegment"},{"kind":"text","text":"]"}],"title":"segments","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7CoreGPX14GPXLegacyTrackC8segmentsSayAA0cD7SegmentCGvp","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrack"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyTrackSegment":{"role":"symbol","title":"GPXLegacyTrackSegment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyTrackSegment"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrackSegment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyTrackSegment"}],"url":"\/documentation\/coregpx\/gpxlegacytracksegment"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyTrack/segments":{"role":"symbol","title":"segments","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"segments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXLegacyTrackSegment","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLegacyTrackSegment"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrack\/segments","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacytrack\/segments"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyTrack":{"role":"symbol","title":"GPXLegacyTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyTrack"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyTrack"}],"url":"\/documentation\/coregpx\/gpxlegacytrack"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyTrackSegment\/title","value":"GPXLegacyTrackSegment"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyTrackSegment\/fragments","value":[{"kind":"identifier","text":"GPXLegacyTrackSegment"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyTrack\/title","value":"GPXLegacyTrack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyTrack\/fragments","value":[{"kind":"identifier","text":"GPXLegacyTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}