{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"upgrade"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrack","text":"GPXTrack"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxlegacytrack\/upgrade()"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrack\/upgrade()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"upgrade"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GPXTrack","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrack"}],"title":"upgrade()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:7CoreGPX14GPXLegacyTrackC7upgradeAA8GPXTrackCyF","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrack"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyTrack":{"role":"symbol","title":"GPXLegacyTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyTrack"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyTrack"}],"url":"\/documentation\/coregpx\/gpxlegacytrack"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyTrack/upgrade()":{"role":"symbol","title":"upgrade()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"upgrade"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GPXTrack","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrack"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrack\/upgrade()","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacytrack\/upgrade()"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack":{"role":"symbol","title":"GPXTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrack"}],"abstract":[{"type":"text","text":"Represents "},{"type":"codeVoice","code":"trkType"},{"type":"text","text":" of GPX v1.1 schema."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXTrack"}],"url":"\/documentation\/coregpx\/gpxtrack"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyTrack\/title","value":"GPXLegacyTrack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyTrack\/fragments","value":[{"kind":"identifier","text":"GPXLegacyTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrack\/title","value":"GPXTrack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrack\/fragments","value":[{"kind":"identifier","text":"GPXTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}