{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extensions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensions","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXExtensions","text":"GPXExtensions"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxroute\/extensions"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoute\/extensions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Extensions"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extensions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXExtensions","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXExtensions"},{"kind":"text","text":"?"}],"title":"extensions","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7CoreGPX8GPXRouteC10extensionsAA13GPXExtensionsCSgvp","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoute"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXExtensions":{"role":"symbol","title":"GPXExtensions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXExtensions"}],"abstract":[{"type":"text","text":"For adding\/obtaining data stored as extensions in GPX file."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXExtensions"}],"url":"\/documentation\/coregpx\/gpxextensions"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoute":{"role":"symbol","title":"GPXRoute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRoute"}],"abstract":[{"type":"text","text":"Value type that represents a route, or "},{"type":"codeVoice","code":"rteType"},{"type":"text","text":" in GPX v1.1 schema."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRoute"}],"url":"\/documentation\/coregpx\/gpxroute"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoute/extensions":{"role":"symbol","title":"extensions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extensions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXExtensions","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXExtensions"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Extensions"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoute\/extensions","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroute\/extensions"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensions\/title","value":"GPXExtensions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensions\/fragments","value":[{"kind":"identifier","text":"GPXExtensions"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoute\/title","value":"GPXRoute"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoute\/fragments","value":[{"kind":"identifier","text":"GPXRoute"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}