{"variants":[{"paths":["\/documentation\/coregpx"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/coregpx"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXAuthor","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXBounds","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCompression","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXEmail","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensions","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensionsElement","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoute","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoutePoint","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrack","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrackPoint","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrackSegment","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLink","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXMetadata","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPerson","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPointSegment","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoute","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoutePoint","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackPoint","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint"]},{"title":"Protocols","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRootElement","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRouteType","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypointProtocol"]},{"title":"Structures","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXError"]},{"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXFix","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXVersion"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"CoreGPX","title":"CoreGPX","symbolKind":"module","role":"collection","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[[]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXExtensionsElement":{"role":"symbol","title":"GPXExtensionsElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXExtensionsElement"}],"abstract":[{"type":"text","text":"A duplicated class of "},{"type":"codeVoice","code":"GPXRawElement"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensionsElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXExtensionsElement"}],"url":"\/documentation\/coregpx\/gpxextensionselement"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXPerson":{"role":"symbol","title":"GPXPerson","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXPerson"}],"abstract":[{"type":"text","text":"A value type that is designated to hold information regarding the person or organisation who has created the GPX file."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPerson","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXPerson"}],"url":"\/documentation\/coregpx\/gpxperson"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXAuthor":{"role":"symbol","title":"GPXAuthor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXAuthor"}],"abstract":[{"type":"text","text":"Author type, holds information of the creator of the GPX file. A subclass of "},{"type":"codeVoice","code":"GPXPerson"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXAuthor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXAuthor"}],"url":"\/documentation\/coregpx\/gpxauthor"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyTrack":{"role":"symbol","title":"GPXLegacyTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyTrack"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyTrack"}],"url":"\/documentation\/coregpx\/gpxlegacytrack"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLink":{"role":"symbol","title":"GPXLink","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLink"}],"abstract":[{"type":"text","text":"A value type that can hold a web link to a external resource, or external information about a certain attribute."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLink","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLink"}],"url":"\/documentation\/coregpx\/gpxlink"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXFix":{"role":"symbol","title":"GPXFix","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXFix"}],"abstract":[{"type":"text","text":"Type of GPS fix."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXFix","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXFix"}],"url":"\/documentation\/coregpx\/gpxfix"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRouteType":{"role":"symbol","title":"GPXRouteType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRouteType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRouteType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRouteType"}],"url":"\/documentation\/coregpx\/gpxroutetype"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot":{"role":"symbol","title":"GPXLegacyRoot","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyRoot"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyRoot"}],"url":"\/documentation\/coregpx\/gpxlegacyroot"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXPoint":{"role":"symbol","title":"GPXPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXPoint"}],"abstract":[{"type":"text","text":"This class ("},{"type":"codeVoice","code":"ptType"},{"type":"text","text":") is added to conform with the GPX v1.1 schema."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXPoint"}],"url":"\/documentation\/coregpx\/gpxpoint"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint":{"role":"symbol","title":"GPXLegacyWaypoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyWaypoint"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyWaypoint"}],"url":"\/documentation\/coregpx\/gpxlegacywaypoint"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot":{"role":"symbol","title":"GPXRoot","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRoot"}],"abstract":[{"type":"text","text":"Creation of a GPX file or GPX formatted string starts here"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRoot"}],"url":"\/documentation\/coregpx\/gpxroot"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoute":{"role":"symbol","title":"GPXRoute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRoute"}],"abstract":[{"type":"text","text":"Value type that represents a route, or "},{"type":"codeVoice","code":"rteType"},{"type":"text","text":" in GPX v1.1 schema."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRoute"}],"url":"\/documentation\/coregpx\/gpxroute"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXPointSegment":{"role":"symbol","title":"GPXPointSegment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXPointSegment"}],"abstract":[{"type":"text","text":"This class ("},{"type":"codeVoice","code":"ptsegType"},{"type":"text","text":") is added to conform with the GPX v1.1 schema."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPointSegment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXPointSegment"}],"url":"\/documentation\/coregpx\/gpxpointsegment"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack":{"role":"symbol","title":"GPXTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrack"}],"abstract":[{"type":"text","text":"Represents "},{"type":"codeVoice","code":"trkType"},{"type":"text","text":" of GPX v1.1 schema."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXTrack"}],"url":"\/documentation\/coregpx\/gpxtrack"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoutePoint":{"role":"symbol","title":"GPXLegacyRoutePoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyRoutePoint"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoutePoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyRoutePoint"}],"url":"\/documentation\/coregpx\/gpxlegacyroutepoint"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyTrackPoint":{"role":"symbol","title":"GPXLegacyTrackPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyTrackPoint"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrackPoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyTrackPoint"}],"url":"\/documentation\/coregpx\/gpxlegacytrackpoint"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXMetadata":{"role":"symbol","title":"GPXMetadata","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXMetadata"}],"abstract":[{"type":"text","text":"A value type that represents the metadata header of a GPX file."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXMetadata"}],"url":"\/documentation\/coregpx\/gpxmetadata"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXCopyright":{"role":"symbol","title":"GPXCopyright","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXCopyright"}],"abstract":[{"type":"text","text":"A value type for representing copyright info"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXCopyright"}],"url":"\/documentation\/coregpx\/gpxcopyright"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXExtensions":{"role":"symbol","title":"GPXExtensions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXExtensions"}],"abstract":[{"type":"text","text":"For adding\/obtaining data stored as extensions in GPX file."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXExtensions"}],"url":"\/documentation\/coregpx\/gpxextensions"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrackPoint":{"role":"symbol","title":"GPXTrackPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrackPoint"}],"abstract":[{"type":"text","text":"A track point is just like a waypoint or route point, but is suited to be part of a track segment."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackPoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXTrackPoint"}],"url":"\/documentation\/coregpx\/gpxtrackpoint"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXError":{"role":"symbol","title":"GPXError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXError"}],"abstract":[{"type":"text","text":"Throwable errors for GPX library"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXError"}],"url":"\/documentation\/coregpx\/gpxerror"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint":{"role":"symbol","title":"GPXWaypoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXWaypoint"}],"abstract":[{"type":"text","text":"A value type that represents waypoint based off GPX v1.1 schema’s "},{"type":"codeVoice","code":"wptType"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXWaypoint"}],"url":"\/documentation\/coregpx\/gpxwaypoint"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/CoreGPXVersionString":{"role":"symbol","title":"CoreGPXVersionString","fragments":[{"kind":"identifier","text":"CoreGPXVersionString"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/CoreGPXVersionString","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/coregpxversionstring"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrackSegment":{"role":"symbol","title":"GPXTrackSegment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrackSegment"}],"abstract":[{"type":"text","text":"A track segment that holds data on all track points in the particular segment."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXTrackSegment"}],"url":"\/documentation\/coregpx\/gpxtracksegment"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXVersion":{"role":"symbol","title":"GPXVersion","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXVersion"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXVersion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXVersion"}],"url":"\/documentation\/coregpx\/gpxversion"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRootElement":{"role":"symbol","title":"GPXRootElement","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRootElement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRootElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRootElement"}],"url":"\/documentation\/coregpx\/gpxrootelement"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXEmail":{"role":"symbol","title":"GPXEmail","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXEmail"}],"abstract":[{"type":"text","text":"Used for handling email types"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXEmail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXEmail"}],"url":"\/documentation\/coregpx\/gpxemail"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXElement":{"role":"symbol","title":"GPXElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXElement"}],"abstract":[{"type":"text","text":"A root class for all element types"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXElement"}],"url":"\/documentation\/coregpx\/gpxelement"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser":{"role":"symbol","title":"GPXParser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXParser"}],"abstract":[{"type":"text","text":"An event-driven parser (SAX parser), currently parses GPX v1.1 files only."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXParser"}],"url":"\/documentation\/coregpx\/gpxparser"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/CoreGPXVersionNumber":{"role":"symbol","title":"CoreGPXVersionNumber","fragments":[{"kind":"identifier","text":"CoreGPXVersionNumber"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/CoreGPXVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/coregpxversionnumber"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypointProtocol":{"role":"symbol","title":"GPXWaypointProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXWaypointProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypointProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXWaypointProtocol"}],"url":"\/documentation\/coregpx\/gpxwaypointprotocol"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoute":{"role":"symbol","title":"GPXLegacyRoute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyRoute"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyRoute"}],"url":"\/documentation\/coregpx\/gpxlegacyroute"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoutePoint":{"role":"symbol","title":"GPXRoutePoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRoutePoint"}],"abstract":[{"type":"text","text":"A route point is just like a waypoint or track point, but is suited to be part of a route."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoutePoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRoutePoint"}],"url":"\/documentation\/coregpx\/gpxroutepoint"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXCompression":{"role":"symbol","title":"GPXCompression","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXCompression"}],"abstract":[{"type":"text","text":"Simple class for some basic lossy compression."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCompression","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXCompression"}],"url":"\/documentation\/coregpx\/gpxcompression"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyTrackSegment":{"role":"symbol","title":"GPXLegacyTrackSegment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyTrackSegment"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrackSegment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyTrackSegment"}],"url":"\/documentation\/coregpx\/gpxlegacytracksegment"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXBounds":{"role":"symbol","title":"GPXBounds","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXBounds"}],"abstract":[{"type":"text","text":"A value type that represents bounds based off GPX v1.1 schema’s "},{"type":"codeVoice","code":"boundsType"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXBounds","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXBounds"}],"url":"\/documentation\/coregpx\/gpxbounds"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXAuthor","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXBounds","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXEmail","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensions","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensionsElement","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoute","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoutePoint","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrack","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrackPoint","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrackSegment","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLink","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXMetadata","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPerson","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPointSegment","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoute","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoutePoint","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackPoint","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint"]},{"title":"Variables","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/CoreGPXVersionNumber","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/CoreGPXVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensionsElement\/title","value":"GPXExtensionsElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensionsElement\/fragments","value":[{"kind":"identifier","text":"GPXExtensionsElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPerson\/title","value":"GPXPerson"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPerson\/fragments","value":[{"kind":"identifier","text":"GPXPerson"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXAuthor\/title","value":"GPXAuthor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXAuthor\/fragments","value":[{"kind":"identifier","text":"GPXAuthor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyTrack\/title","value":"GPXLegacyTrack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyTrack\/fragments","value":[{"kind":"identifier","text":"GPXLegacyTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLink\/title","value":"GPXLink"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLink\/fragments","value":[{"kind":"identifier","text":"GPXLink"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoot\/title","value":"GPXLegacyRoot"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoot\/fragments","value":[{"kind":"identifier","text":"GPXLegacyRoot"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPoint\/title","value":"GPXPoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPoint\/fragments","value":[{"kind":"identifier","text":"GPXPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyWaypoint\/title","value":"GPXLegacyWaypoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyWaypoint\/fragments","value":[{"kind":"identifier","text":"GPXLegacyWaypoint"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoot\/title","value":"GPXRoot"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoot\/fragments","value":[{"kind":"identifier","text":"GPXRoot"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoute\/title","value":"GPXRoute"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoute\/fragments","value":[{"kind":"identifier","text":"GPXRoute"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPointSegment\/title","value":"GPXPointSegment"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPointSegment\/fragments","value":[{"kind":"identifier","text":"GPXPointSegment"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrack\/title","value":"GPXTrack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrack\/fragments","value":[{"kind":"identifier","text":"GPXTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoutePoint\/title","value":"GPXLegacyRoutePoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoutePoint\/fragments","value":[{"kind":"identifier","text":"GPXLegacyRoutePoint"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyTrackPoint\/title","value":"GPXLegacyTrackPoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyTrackPoint\/fragments","value":[{"kind":"identifier","text":"GPXLegacyTrackPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXMetadata\/title","value":"GPXMetadata"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXMetadata\/fragments","value":[{"kind":"identifier","text":"GPXMetadata"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXCopyright\/title","value":"GPXCopyright"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXCopyright\/fragments","value":[{"kind":"identifier","text":"GPXCopyright"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensions\/title","value":"GPXExtensions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensions\/fragments","value":[{"kind":"identifier","text":"GPXExtensions"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackPoint\/title","value":"GPXTrackPoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackPoint\/fragments","value":[{"kind":"identifier","text":"GPXTrackPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXWaypoint\/title","value":"GPXWaypoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXWaypoint\/fragments","value":[{"kind":"identifier","text":"GPXWaypoint"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackSegment\/title","value":"GPXTrackSegment"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackSegment\/fragments","value":[{"kind":"identifier","text":"GPXTrackSegment"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXEmail\/title","value":"GPXEmail"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXEmail\/fragments","value":[{"kind":"identifier","text":"GPXEmail"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/title","value":"GPXElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/fragments","value":[{"kind":"identifier","text":"GPXElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser\/title","value":"GPXParser"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser\/fragments","value":[{"kind":"identifier","text":"GPXParser"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoute\/title","value":"GPXLegacyRoute"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoute\/fragments","value":[{"kind":"identifier","text":"GPXLegacyRoute"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoutePoint\/title","value":"GPXRoutePoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoutePoint\/fragments","value":[{"kind":"identifier","text":"GPXRoutePoint"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyTrackSegment\/title","value":"GPXLegacyTrackSegment"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyTrackSegment\/fragments","value":[{"kind":"identifier","text":"GPXLegacyTrackSegment"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXBounds\/title","value":"GPXBounds"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXBounds\/fragments","value":[{"kind":"identifier","text":"GPXBounds"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}