{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloaderDelegate","preciseIdentifier":"c:@M@MapCache@objc(pl)RegionDownloaderDelegate","text":"RegionDownloaderDelegate"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapcache\/regiondownloader\/delegate"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/delegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Delegate."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RegionDownloaderDelegate","preciseIdentifier":"c:@M@MapCache@objc(pl)RegionDownloaderDelegate"},{"kind":"text","text":"?"}],"title":"delegate","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:8MapCache16RegionDownloaderC8delegateAA0cD8Delegate_pSgvp","modules":[{"name":"MapCache"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader"]]},"references":{"doc://org.cocoapods.MapCache/documentation/MapCache":{"role":"collection","title":"MapCache","abstract":[],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache","kind":"symbol","type":"topic","url":"\/documentation\/mapcache"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RegionDownloaderDelegate","preciseIdentifier":"c:@M@MapCache@objc(pl)RegionDownloaderDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Delegate."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/mapcache\/regiondownloader\/delegate"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloaderDelegate":{"role":"symbol","title":"RegionDownloaderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegionDownloaderDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol of "},{"type":"codeVoice","code":"RegionDownloader"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Implement this protocol whenever  you use "},{"type":"codeVoice","code":"RegionDownloader"},{"type":"text","text":" it drovides feedback while donwloading a"},{"type":"text","text":" "},{"type":"text","text":"region (f.i, downloaded %) and callsback the delegate once the download finished."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloaderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RegionDownloaderDelegate"}],"url":"\/documentation\/mapcache\/regiondownloaderdelegate"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader":{"role":"symbol","title":"RegionDownloader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegionDownloader"}],"abstract":[{"type":"text","text":"Hey! I need to download this area of the map."},{"type":"text","text":" "},{"type":"text","text":"No problemo."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RegionDownloader"}],"url":"\/documentation\/mapcache\/regiondownloader"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloaderDelegate\/title","value":"RegionDownloaderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloaderDelegate\/fragments","value":[{"kind":"identifier","text":"RegionDownloaderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloader\/title","value":"RegionDownloader"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloader\/fragments","value":[{"kind":"identifier","text":"RegionDownloader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}