{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"dynamic"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedTileDownloads"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/TileNumber","preciseIdentifier":"s:8MapCache10TileNumbera","text":"TileNumber"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapcache\/regiondownloader\/failedtiledownloads"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapcache\/regiondownloader\/failedtiledownloads"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/failedTileDownloads","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Number of tiles to be downloaded"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedTileDownloads"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TileNumber","preciseIdentifier":"s:8MapCache10TileNumbera"}],"title":"failedTileDownloads","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@MapCache@objc(cs)RegionDownloader(py)failedTileDownloads","modules":[{"name":"MapCache"}],"navigatorTitle":[{"kind":"identifier","text":"failedTileDownloads"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader"]]},"references":{"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader/failedTileDownloads":{"role":"symbol","title":"failedTileDownloads","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedTileDownloads"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TileNumber","preciseIdentifier":"s:8MapCache10TileNumbera"}],"abstract":[{"type":"text","text":"Number of tiles to be downloaded"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader\/failedTileDownloads","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"failedTileDownloads"}],"url":"\/documentation\/mapcache\/regiondownloader\/failedtiledownloads"},"doc://org.cocoapods.MapCache/documentation/MapCache":{"role":"collection","title":"MapCache","abstract":[],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache","kind":"symbol","type":"topic","url":"\/documentation\/mapcache"},"doc://org.cocoapods.MapCache/documentation/MapCache/TileNumber":{"role":"symbol","title":"TileNumber","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileNumber"}],"abstract":[{"type":"text","text":"Tile number in a map."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/TileNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileNumber"}],"url":"\/documentation\/mapcache\/tilenumber"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader":{"role":"symbol","title":"RegionDownloader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegionDownloader"}],"abstract":[{"type":"text","text":"Hey! I need to download this area of the map."},{"type":"text","text":" "},{"type":"text","text":"No problemo."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RegionDownloader"}],"url":"\/documentation\/mapcache\/regiondownloader"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"failedTileDownloads"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"failedTileDownloads"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"uint64_t","preciseIdentifier":"c:@T@uint64_t"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedTileDownloads"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloader~1failedTileDownloads\/title","value":"failedTileDownloads"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloader~1failedTileDownloads\/fragments","value":[{"kind":"identifier","text":"failedTileDownloads"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloader\/title","value":"RegionDownloader"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloader\/fragments","value":[{"kind":"identifier","text":"RegionDownloader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}