{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXEmail","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXEmail","text":"GPXEmail"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"link"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLink","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLink","text":"GPXLink"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxauthor\/init(name:email:link:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXAuthor\/init(name:email:link:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXEmail","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXEmail"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"link"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXLink","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLink"},{"kind":"text","text":"?)"}],"title":"init(name:email:link:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:7CoreGPX9GPXAuthorC4name5email4linkACSSSg_AA8GPXEmailCSgAA7GPXLinkCSgtcfc","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXAuthor"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXEmail":{"role":"symbol","title":"GPXEmail","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXEmail"}],"abstract":[{"type":"text","text":"Used for handling email types"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXEmail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXEmail"}],"url":"\/documentation\/coregpx\/gpxemail"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLink":{"role":"symbol","title":"GPXLink","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLink"}],"abstract":[{"type":"text","text":"A value type that can hold a web link to a external resource, or external information about a certain attribute."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLink","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLink"}],"url":"\/documentation\/coregpx\/gpxlink"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXAuthor":{"role":"symbol","title":"GPXAuthor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXAuthor"}],"abstract":[{"type":"text","text":"Author type, holds information of the creator of the GPX file. A subclass of "},{"type":"codeVoice","code":"GPXPerson"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXAuthor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXAuthor"}],"url":"\/documentation\/coregpx\/gpxauthor"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXAuthor/init(name:email:link:)":{"role":"symbol","title":"init(name:email:link:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXEmail","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXEmail"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"link"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXLink","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLink"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXAuthor\/init(name:email:link:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxauthor\/init(name:email:link:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXEmail\/title","value":"GPXEmail"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXEmail\/fragments","value":[{"kind":"identifier","text":"GPXEmail"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLink\/title","value":"GPXLink"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLink\/fragments","value":[{"kind":"identifier","text":"GPXLink"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXAuthor\/title","value":"GPXAuthor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXAuthor\/fragments","value":[{"kind":"identifier","text":"GPXAuthor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}