{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extensions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensions","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXExtensions","text":"GPXExtensions"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"leave it as is, if used without modification to GPX schema"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxroot\/extensions"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/extensions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Items for extensions to GPX schema (if any)"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extensions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXExtensions","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXExtensions"},{"kind":"text","text":"?"}],"title":"extensions","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7CoreGPX7GPXRootC10extensionsAA13GPXExtensionsCSgvp","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/extensions":{"role":"symbol","title":"extensions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extensions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXExtensions","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXExtensions"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Items for extensions to GPX schema (if any)"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/extensions","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/extensions"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXExtensions":{"role":"symbol","title":"GPXExtensions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXExtensions"}],"abstract":[{"type":"text","text":"For adding\/obtaining data stored as extensions in GPX file."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXExtensions"}],"url":"\/documentation\/coregpx\/gpxextensions"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot":{"role":"symbol","title":"GPXRoot","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRoot"}],"abstract":[{"type":"text","text":"Creation of a GPX file or GPX formatted string starts here"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRoot"}],"url":"\/documentation\/coregpx\/gpxroot"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensions\/title","value":"GPXExtensions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensions\/fragments","value":[{"kind":"identifier","text":"GPXExtensions"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoot\/title","value":"GPXRoot"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoot\/fragments","value":[{"kind":"identifier","text":"GPXRoot"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}