{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newRoute"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoute","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXRoute","text":"GPXRoute"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"A "},{"type":"codeVoice","code":"GPXRoute"},{"type":"text","text":" object."}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A route is initialized, then added into the array of routes in this "},{"type":"codeVoice","code":"GPXRoot"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxroot\/newroute()"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/newRoute()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"route"},{"type":"text","text":" which is also added to "},{"type":"codeVoice","code":"GPXRoot"},{"type":"text","text":" automatically"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newRoute"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GPXRoute","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXRoute"}],"title":"newRoute()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:7CoreGPX7GPXRootC8newRouteAA8GPXRouteCyF","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoute":{"role":"symbol","title":"GPXRoute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRoute"}],"abstract":[{"type":"text","text":"Value type that represents a route, or "},{"type":"codeVoice","code":"rteType"},{"type":"text","text":" in GPX v1.1 schema."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRoute"}],"url":"\/documentation\/coregpx\/gpxroute"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/newRoute()":{"role":"symbol","title":"newRoute()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newRoute"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GPXRoute","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXRoute"}],"abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"route"},{"type":"text","text":" which is also added to "},{"type":"codeVoice","code":"GPXRoot"},{"type":"text","text":" automatically"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/newRoute()","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/newroute()"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot":{"role":"symbol","title":"GPXRoot","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRoot"}],"abstract":[{"type":"text","text":"Creation of a GPX file or GPX formatted string starts here"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRoot"}],"url":"\/documentation\/coregpx\/gpxroot"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoute\/title","value":"GPXRoute"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoute\/fragments","value":[{"kind":"identifier","text":"GPXRoute"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoot\/title","value":"GPXRoot"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoot\/fragments","value":[{"kind":"identifier","text":"GPXRoot"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}