{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoute","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXRoute","text":"GPXRoute"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxroot\/routes"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/routes","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Array of routes"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXRoute","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXRoute"},{"kind":"text","text":"]"}],"title":"routes","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7CoreGPX7GPXRootC6routesSayAA8GPXRouteCGvp","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoute":{"role":"symbol","title":"GPXRoute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRoute"}],"abstract":[{"type":"text","text":"Value type that represents a route, or "},{"type":"codeVoice","code":"rteType"},{"type":"text","text":" in GPX v1.1 schema."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRoute"}],"url":"\/documentation\/coregpx\/gpxroute"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/routes":{"role":"symbol","title":"routes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXRoute","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXRoute"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Array of routes"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/routes","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/routes"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot":{"role":"symbol","title":"GPXRoot","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRoot"}],"abstract":[{"type":"text","text":"Creation of a GPX file or GPX formatted string starts here"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRoot"}],"url":"\/documentation\/coregpx\/gpxroot"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoute\/title","value":"GPXRoute"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoute\/fragments","value":[{"kind":"identifier","text":"GPXRoute"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoot\/title","value":"GPXRoot"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoot\/fragments","value":[{"kind":"identifier","text":"GPXRoot"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}