{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXCopyright"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Copyight information also includes additional attributes."}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Supported attributes:"}]}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Year of first publication"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"License of the file"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Author \/ Copyright Holder’s name"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxcopyright"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/coregpx\/gpxcopyright"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSObject","doc:\/\/org.cocoapods.CoreGPX\/s7CVarArgP","doc:\/\/org.cocoapods.CoreGPX\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.CoreGPX\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.CoreGPX\/Se","doc:\/\/org.cocoapods.CoreGPX\/SE","doc:\/\/org.cocoapods.CoreGPX\/SQ","doc:\/\/org.cocoapods.CoreGPX\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A value type for representing copyright info"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXCopyright"}],"title":"GPXCopyright","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CoreGPX@objc(cs)GPXCopyright","modules":[{"name":"CoreGPX"}],"navigatorTitle":[{"kind":"identifier","text":"GPXCopyright"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright\/init()","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright\/init(author:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright\/author","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright\/license","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright\/year"]}],"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXCopyright":{"role":"symbol","title":"GPXCopyright","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXCopyright"}],"abstract":[{"type":"text","text":"A value type for representing copyright info"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXCopyright"}],"url":"\/documentation\/coregpx\/gpxcopyright"},"doc://org.cocoapods.CoreGPX/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/Se"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXCopyright/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxcopyright\/init(from:)"},"doc://org.cocoapods.CoreGPX/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXElement":{"role":"symbol","title":"GPXElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXElement"}],"abstract":[{"type":"text","text":"A root class for all element types"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXElement"}],"url":"\/documentation\/coregpx\/gpxelement"},"doc://org.cocoapods.CoreGPX/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SQ"},"doc://org.cocoapods.CoreGPX/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SE"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXCopyright/license":{"role":"symbol","title":"license","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"license"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"License of the file."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright\/license","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxcopyright\/license"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXCopyright/init(author:)":{"role":"symbol","title":"init(author:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"author"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes with author"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright\/init(author:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxcopyright\/init(author:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXCopyright/year":{"role":"symbol","title":"year","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"year"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Year of the first publication of this copyrighted work."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright\/year","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxcopyright\/year"},"doc://org.cocoapods.CoreGPX/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s23CustomStringConvertibleP"},"doc://org.cocoapods.CoreGPX/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SH"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXCopyright/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Default Initializer."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/coregpx\/gpxcopyright\/init()"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXCopyright/author":{"role":"symbol","title":"author","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"author"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Author \/ copyright holder’s name."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright\/author","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxcopyright\/author"},"doc://org.cocoapods.CoreGPX/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s7CVarArgP"},"doc://org.cocoapods.CoreGPX/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GPXCopyright"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GPXCopyright"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GPXCopyright"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright\/init()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXCopyright"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXElement","text":"GPXElement"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXCopyright\/title","value":"GPXCopyright"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXCopyright\/fragments","value":[{"kind":"identifier","text":"GPXCopyright"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/title","value":"GPXElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/fragments","value":[{"kind":"identifier","text":"GPXElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXCopyright~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXCopyright~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}