{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXElement"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"All element types such as waypoints, tracks or routes are subclasses of "},{"type":"codeVoice","code":"GPXElement"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This class brings important methods that aids towards creation of a GPX file."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxelement"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/coregpx\/gpxelement"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXBounds","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXEmail","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensions","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensionsElement","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoute","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrack","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrackSegment","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLink","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXMetadata","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPerson","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPointSegment","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRootElement","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoute","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypointProtocol"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSObject","doc:\/\/org.cocoapods.CoreGPX\/s7CVarArgP","doc:\/\/org.cocoapods.CoreGPX\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.CoreGPX\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.CoreGPX\/SQ","doc:\/\/org.cocoapods.CoreGPX\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A root class for all element types"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXElement"}],"title":"GPXElement","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CoreGPX@objc(cs)GPXElement","modules":[{"name":"CoreGPX"}],"navigatorTitle":[{"kind":"identifier","text":"GPXElement"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement\/init()"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement\/gpx()"]}],"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXElement/gpx()":{"role":"symbol","title":"gpx()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gpx"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"for generating newly tracked data straight into a formatted "},{"type":"codeVoice","code":"String"},{"type":"text","text":" that holds formatted data according to GPX syntax"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement\/gpx()","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxelement\/gpx()"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyTrackSegment":{"role":"symbol","title":"GPXLegacyTrackSegment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyTrackSegment"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrackSegment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyTrackSegment"}],"url":"\/documentation\/coregpx\/gpxlegacytracksegment"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack":{"role":"symbol","title":"GPXTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrack"}],"abstract":[{"type":"text","text":"Represents "},{"type":"codeVoice","code":"trkType"},{"type":"text","text":" of GPX v1.1 schema."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXTrack"}],"url":"\/documentation\/coregpx\/gpxtrack"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot":{"role":"symbol","title":"GPXRoot","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRoot"}],"abstract":[{"type":"text","text":"Creation of a GPX file or GPX formatted string starts here"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRoot"}],"url":"\/documentation\/coregpx\/gpxroot"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXMetadata":{"role":"symbol","title":"GPXMetadata","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXMetadata"}],"abstract":[{"type":"text","text":"A value type that represents the metadata header of a GPX file."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXMetadata"}],"url":"\/documentation\/coregpx\/gpxmetadata"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot":{"role":"symbol","title":"GPXLegacyRoot","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyRoot"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyRoot"}],"url":"\/documentation\/coregpx\/gpxlegacyroot"},"doc://org.cocoapods.CoreGPX/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.CoreGPX\/objc(cs)NSObject"},"doc://org.cocoapods.CoreGPX/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s23CustomStringConvertibleP"},"doc://org.cocoapods.CoreGPX/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSObject"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypointProtocol":{"role":"symbol","title":"GPXWaypointProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXWaypointProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypointProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXWaypointProtocol"}],"url":"\/documentation\/coregpx\/gpxwaypointprotocol"},"doc://org.cocoapods.CoreGPX/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SH"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrackSegment":{"role":"symbol","title":"GPXTrackSegment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrackSegment"}],"abstract":[{"type":"text","text":"A track segment that holds data on all track points in the particular segment."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXTrackSegment"}],"url":"\/documentation\/coregpx\/gpxtracksegment"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXPoint":{"role":"symbol","title":"GPXPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXPoint"}],"abstract":[{"type":"text","text":"This class ("},{"type":"codeVoice","code":"ptType"},{"type":"text","text":") is added to conform with the GPX v1.1 schema."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXPoint"}],"url":"\/documentation\/coregpx\/gpxpoint"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXPerson":{"role":"symbol","title":"GPXPerson","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXPerson"}],"abstract":[{"type":"text","text":"A value type that is designated to hold information regarding the person or organisation who has created the GPX file."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPerson","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXPerson"}],"url":"\/documentation\/coregpx\/gpxperson"},"doc://org.cocoapods.CoreGPX/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXExtensions":{"role":"symbol","title":"GPXExtensions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXExtensions"}],"abstract":[{"type":"text","text":"For adding\/obtaining data stored as extensions in GPX file."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXExtensions"}],"url":"\/documentation\/coregpx\/gpxextensions"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXBounds":{"role":"symbol","title":"GPXBounds","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXBounds"}],"abstract":[{"type":"text","text":"A value type that represents bounds based off GPX v1.1 schema’s "},{"type":"codeVoice","code":"boundsType"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXBounds","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXBounds"}],"url":"\/documentation\/coregpx\/gpxbounds"},"doc://org.cocoapods.CoreGPX/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s7CVarArgP"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXElement/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Default Initializer"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/coregpx\/gpxelement\/init()"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRootElement":{"role":"symbol","title":"GPXRootElement","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRootElement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRootElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRootElement"}],"url":"\/documentation\/coregpx\/gpxrootelement"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXPointSegment":{"role":"symbol","title":"GPXPointSegment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXPointSegment"}],"abstract":[{"type":"text","text":"This class ("},{"type":"codeVoice","code":"ptsegType"},{"type":"text","text":") is added to conform with the GPX v1.1 schema."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPointSegment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXPointSegment"}],"url":"\/documentation\/coregpx\/gpxpointsegment"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint":{"role":"symbol","title":"GPXLegacyWaypoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyWaypoint"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyWaypoint"}],"url":"\/documentation\/coregpx\/gpxlegacywaypoint"},"doc://org.cocoapods.CoreGPX/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SQ"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXExtensionsElement":{"role":"symbol","title":"GPXExtensionsElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXExtensionsElement"}],"abstract":[{"type":"text","text":"A duplicated class of "},{"type":"codeVoice","code":"GPXRawElement"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensionsElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXExtensionsElement"}],"url":"\/documentation\/coregpx\/gpxextensionselement"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoute":{"role":"symbol","title":"GPXRoute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRoute"}],"abstract":[{"type":"text","text":"Value type that represents a route, or "},{"type":"codeVoice","code":"rteType"},{"type":"text","text":" in GPX v1.1 schema."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRoute"}],"url":"\/documentation\/coregpx\/gpxroute"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLink":{"role":"symbol","title":"GPXLink","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLink"}],"abstract":[{"type":"text","text":"A value type that can hold a web link to a external resource, or external information about a certain attribute."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLink","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLink"}],"url":"\/documentation\/coregpx\/gpxlink"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXEmail":{"role":"symbol","title":"GPXEmail","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXEmail"}],"abstract":[{"type":"text","text":"Used for handling email types"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXEmail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXEmail"}],"url":"\/documentation\/coregpx\/gpxemail"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoute":{"role":"symbol","title":"GPXLegacyRoute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyRoute"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyRoute"}],"url":"\/documentation\/coregpx\/gpxlegacyroute"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXCopyright":{"role":"symbol","title":"GPXCopyright","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXCopyright"}],"abstract":[{"type":"text","text":"A value type for representing copyright info"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXCopyright"}],"url":"\/documentation\/coregpx\/gpxcopyright"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint":{"role":"symbol","title":"GPXWaypoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXWaypoint"}],"abstract":[{"type":"text","text":"A value type that represents waypoint based off GPX v1.1 schema’s "},{"type":"codeVoice","code":"wptType"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXWaypoint"}],"url":"\/documentation\/coregpx\/gpxwaypoint"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyTrack":{"role":"symbol","title":"GPXLegacyTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyTrack"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyTrack"}],"url":"\/documentation\/coregpx\/gpxlegacytrack"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXElement":{"role":"symbol","title":"GPXElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXElement"}],"abstract":[{"type":"text","text":"A root class for all element types"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXElement"}],"url":"\/documentation\/coregpx\/gpxelement"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GPXElement"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GPXElement"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GPXElement"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement\/init()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXBounds","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXCopyright","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXEmail","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensions","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensionsElement","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoute","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrack","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrackSegment","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLink","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXMetadata","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPerson","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPointSegment","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoute","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXElement"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyTrackSegment\/title","value":"GPXLegacyTrackSegment"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyTrackSegment\/fragments","value":[{"kind":"identifier","text":"GPXLegacyTrackSegment"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrack\/title","value":"GPXTrack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrack\/fragments","value":[{"kind":"identifier","text":"GPXTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoot\/title","value":"GPXRoot"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoot\/fragments","value":[{"kind":"identifier","text":"GPXRoot"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXMetadata\/title","value":"GPXMetadata"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXMetadata\/fragments","value":[{"kind":"identifier","text":"GPXMetadata"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoot\/title","value":"GPXLegacyRoot"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoot\/fragments","value":[{"kind":"identifier","text":"GPXLegacyRoot"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackSegment\/title","value":"GPXTrackSegment"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackSegment\/fragments","value":[{"kind":"identifier","text":"GPXTrackSegment"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPoint\/title","value":"GPXPoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPoint\/fragments","value":[{"kind":"identifier","text":"GPXPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPerson\/title","value":"GPXPerson"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPerson\/fragments","value":[{"kind":"identifier","text":"GPXPerson"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensions\/title","value":"GPXExtensions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensions\/fragments","value":[{"kind":"identifier","text":"GPXExtensions"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXBounds\/title","value":"GPXBounds"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXBounds\/fragments","value":[{"kind":"identifier","text":"GPXBounds"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPointSegment\/title","value":"GPXPointSegment"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPointSegment\/fragments","value":[{"kind":"identifier","text":"GPXPointSegment"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyWaypoint\/title","value":"GPXLegacyWaypoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyWaypoint\/fragments","value":[{"kind":"identifier","text":"GPXLegacyWaypoint"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensionsElement\/title","value":"GPXExtensionsElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensionsElement\/fragments","value":[{"kind":"identifier","text":"GPXExtensionsElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoute\/title","value":"GPXRoute"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoute\/fragments","value":[{"kind":"identifier","text":"GPXRoute"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLink\/title","value":"GPXLink"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLink\/fragments","value":[{"kind":"identifier","text":"GPXLink"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXEmail\/title","value":"GPXEmail"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXEmail\/fragments","value":[{"kind":"identifier","text":"GPXEmail"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoute\/title","value":"GPXLegacyRoute"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoute\/fragments","value":[{"kind":"identifier","text":"GPXLegacyRoute"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXCopyright\/title","value":"GPXCopyright"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXCopyright\/fragments","value":[{"kind":"identifier","text":"GPXCopyright"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXWaypoint\/title","value":"GPXWaypoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXWaypoint\/fragments","value":[{"kind":"identifier","text":"GPXWaypoint"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyTrack\/title","value":"GPXLegacyTrack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyTrack\/fragments","value":[{"kind":"identifier","text":"GPXLegacyTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/title","value":"GPXElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/fragments","value":[{"kind":"identifier","text":"GPXElement"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}