{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyRoot"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxlegacyroot"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/coregpx\/gpxlegacyroot"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRootElement","doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSObject","doc:\/\/org.cocoapods.CoreGPX\/s7CVarArgP","doc:\/\/org.cocoapods.CoreGPX\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.CoreGPX\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.CoreGPX\/SQ","doc:\/\/org.cocoapods.CoreGPX\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/init()","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/init(creator:version:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/author","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/bounds","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/creator","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/desc","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/email","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/keywords","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/name","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/routes","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/time","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/tracks","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/url","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/urlName","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/version","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/waypoints"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/addEmail(_:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/upgrade()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyRoot"}],"title":"GPXLegacyRoot","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CoreGPX@objc(cs)GPXLegacyRoot","modules":[{"name":"CoreGPX"}],"navigatorTitle":[{"kind":"identifier","text":"GPXLegacyRoot"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot/routes":{"role":"symbol","title":"routes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXLegacyRoute","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLegacyRoute"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/routes","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacyroot\/routes"},"doc://org.cocoapods.CoreGPX/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SH"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot/url":{"role":"symbol","title":"url","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/url","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacyroot\/url"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot/version":{"role":"symbol","title":"version","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"version"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXVersion","preciseIdentifier":"s:7CoreGPX10GPXVersionO"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/version","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacyroot\/version"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRootElement":{"role":"symbol","title":"GPXRootElement","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRootElement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRootElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRootElement"}],"url":"\/documentation\/coregpx\/gpxrootelement"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot/desc":{"role":"symbol","title":"desc","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"desc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/desc","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacyroot\/desc"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot/tracks":{"role":"symbol","title":"tracks","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tracks"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXLegacyTrack","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLegacyTrack"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/tracks","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacyroot\/tracks"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXElement":{"role":"symbol","title":"GPXElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXElement"}],"abstract":[{"type":"text","text":"A root class for all element types"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXElement"}],"url":"\/documentation\/coregpx\/gpxelement"},"doc://org.cocoapods.CoreGPX/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s23CustomStringConvertibleP"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot/urlName":{"role":"symbol","title":"urlName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/urlName","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacyroot\/urlname"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot/email":{"role":"symbol","title":"email","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/email","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacyroot\/email"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot/time":{"role":"symbol","title":"time","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/time","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacyroot\/time"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot/addEmail(_:)":{"role":"symbol","title":"addEmail(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addEmail"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/addEmail(_:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacyroot\/addemail(_:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot/bounds":{"role":"symbol","title":"bounds","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bounds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXBounds","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXBounds"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/bounds","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacyroot\/bounds"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot/init(creator:version:)":{"role":"symbol","title":"init(creator:version:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"creator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"version"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXVersion","preciseIdentifier":"s:7CoreGPX10GPXVersionO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/init(creator:version:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacyroot\/init(creator:version:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot/keywords":{"role":"symbol","title":"keywords","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keywords"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/keywords","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacyroot\/keywords"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot/creator":{"role":"symbol","title":"creator","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"creator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/creator","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacyroot\/creator"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot":{"role":"symbol","title":"GPXLegacyRoot","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyRoot"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyRoot"}],"url":"\/documentation\/coregpx\/gpxlegacyroot"},"doc://org.cocoapods.CoreGPX/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot/waypoints":{"role":"symbol","title":"waypoints","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"waypoints"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXLegacyWaypoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLegacyWaypoint"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/waypoints","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacyroot\/waypoints"},"doc://org.cocoapods.CoreGPX/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSObject"},"doc://org.cocoapods.CoreGPX/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s7CVarArgP"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot/author":{"role":"symbol","title":"author","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"author"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/author","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacyroot\/author"},"doc://org.cocoapods.CoreGPX/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SQ"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Default Initializer"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/coregpx\/gpxlegacyroot\/init()"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot/upgrade()":{"role":"symbol","title":"upgrade()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"upgrade"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GPXRoot","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXRoot"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/upgrade()","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacyroot\/upgrade()"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/name","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacyroot\/name"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GPXLegacyRoot"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GPXLegacyRoot"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GPXLegacyRoot"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot\/init()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyRoot"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXElement","text":"GPXElement"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/title","value":"GPXElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/fragments","value":[{"kind":"identifier","text":"GPXElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoot\/title","value":"GPXLegacyRoot"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoot\/fragments","value":[{"kind":"identifier","text":"GPXLegacyRoot"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoot~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoot~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}