{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyWaypoint"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxlegacywaypoint"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/coregpx\/gpxlegacywaypoint"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoutePoint","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrackPoint"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypointProtocol","doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSObject","doc:\/\/org.cocoapods.CoreGPX\/s7CVarArgP","doc:\/\/org.cocoapods.CoreGPX\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.CoreGPX\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.CoreGPX\/SQ","doc:\/\/org.cocoapods.CoreGPX\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/DGPSid","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/ageofDGPSData","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/comment","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/desc","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/elevation","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/fix","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/geoidHeight","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/horizontalDilution","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/latitude","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/longitude","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/magneticVariation","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/name","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/positionDilution","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/satellites","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/source","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/symbol","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/time","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/type","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/url","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/urlName","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/verticalDilution"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyWaypoint"}],"title":"GPXLegacyWaypoint","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CoreGPX@objc(cs)GPXLegacyWaypoint","modules":[{"name":"CoreGPX"}],"navigatorTitle":[{"kind":"identifier","text":"GPXLegacyWaypoint"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/symbol":{"role":"symbol","title":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"symbol"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Text of GPS symbol name"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/symbol","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacywaypoint\/symbol"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/source":{"role":"symbol","title":"source","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Source of data of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/source","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacywaypoint\/source"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/satellites":{"role":"symbol","title":"satellites","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"satellites"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Number of satellites used to calculate GPS fix of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/satellites","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacywaypoint\/satellites"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypointProtocol":{"role":"symbol","title":"GPXWaypointProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXWaypointProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypointProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXWaypointProtocol"}],"url":"\/documentation\/coregpx\/gpxwaypointprotocol"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/latitude":{"role":"symbol","title":"latitude","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Latitude of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/latitude","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacywaypoint\/latitude"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/time":{"role":"symbol","title":"time","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Date and time of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/time","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacywaypoint\/time"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/DGPSid":{"role":"symbol","title":"DGPSid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"DGPSid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"DGPS’ ID"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/DGPSid","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacywaypoint\/dgpsid"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/longitude":{"role":"symbol","title":"longitude","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"longitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Longitude of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/longitude","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacywaypoint\/longitude"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/elevation":{"role":"symbol","title":"elevation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"elevation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Elevation of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/elevation","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacywaypoint\/elevation"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/magneticVariation":{"role":"symbol","title":"magneticVariation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"magneticVariation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Magnetic Variation of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/magneticVariation","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacywaypoint\/magneticvariation"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Type of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/type","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacywaypoint\/type"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/positionDilution":{"role":"symbol","title":"positionDilution","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"positionDilution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Position dilution of precision of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/positionDilution","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacywaypoint\/positiondilution"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/comment":{"role":"symbol","title":"comment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"comment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Comment of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/comment","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacywaypoint\/comment"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/ageofDGPSData":{"role":"symbol","title":"ageofDGPSData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ageofDGPSData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Age of DGPS Data"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/ageofDGPSData","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacywaypoint\/ageofdgpsdata"},"doc://org.cocoapods.CoreGPX/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SH"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoutePoint":{"role":"symbol","title":"GPXLegacyRoutePoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyRoutePoint"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoutePoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyRoutePoint"}],"url":"\/documentation\/coregpx\/gpxlegacyroutepoint"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Name of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/name","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacywaypoint\/name"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/url":{"role":"symbol","title":"url","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"URL of this particular waypoint, if any."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/url","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacywaypoint\/url"},"doc://org.cocoapods.CoreGPX/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SQ"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/fix":{"role":"symbol","title":"fix","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fix"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXFix","preciseIdentifier":"s:7CoreGPX6GPXFixO"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Type of GPS fix of current point, represented as a number"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/fix","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacywaypoint\/fix"},"doc://org.cocoapods.CoreGPX/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXElement":{"role":"symbol","title":"GPXElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXElement"}],"abstract":[{"type":"text","text":"A root class for all element types"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXElement"}],"url":"\/documentation\/coregpx\/gpxelement"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/verticalDilution":{"role":"symbol","title":"verticalDilution","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"verticalDilution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Vertical dilution of precision of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/verticalDilution","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacywaypoint\/verticaldilution"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/geoidHeight":{"role":"symbol","title":"geoidHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"geoidHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Geoid Height of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/geoidHeight","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacywaypoint\/geoidheight"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/horizontalDilution":{"role":"symbol","title":"horizontalDilution","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"horizontalDilution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Horizontal dilution of precision of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/horizontalDilution","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacywaypoint\/horizontaldilution"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint":{"role":"symbol","title":"GPXLegacyWaypoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyWaypoint"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyWaypoint"}],"url":"\/documentation\/coregpx\/gpxlegacywaypoint"},"doc://org.cocoapods.CoreGPX/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSObject"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/urlName":{"role":"symbol","title":"urlName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Name associated with the given URL."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/urlName","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacywaypoint\/urlname"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyTrackPoint":{"role":"symbol","title":"GPXLegacyTrackPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyTrackPoint"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrackPoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyTrackPoint"}],"url":"\/documentation\/coregpx\/gpxlegacytrackpoint"},"doc://org.cocoapods.CoreGPX/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s7CVarArgP"},"doc://org.cocoapods.CoreGPX/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s23CustomStringConvertibleP"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/desc":{"role":"symbol","title":"desc","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"desc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Description of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/desc","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacywaypoint\/desc"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyWaypoint/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Default Initializer"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/coregpx\/gpxlegacywaypoint\/init()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GPXLegacyWaypoint"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GPXLegacyWaypoint"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GPXLegacyWaypoint"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyWaypoint\/init()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoutePoint","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyTrackPoint"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyWaypoint"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXElement","text":"GPXElement"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoutePoint\/title","value":"GPXLegacyRoutePoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoutePoint\/fragments","value":[{"kind":"identifier","text":"GPXLegacyRoutePoint"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/title","value":"GPXElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/fragments","value":[{"kind":"identifier","text":"GPXElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyWaypoint\/title","value":"GPXLegacyWaypoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyWaypoint\/fragments","value":[{"kind":"identifier","text":"GPXLegacyWaypoint"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyTrackPoint\/title","value":"GPXLegacyTrackPoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyTrackPoint\/fragments","value":[{"kind":"identifier","text":"GPXLegacyTrackPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyWaypoint~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyWaypoint~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}