{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXPoint"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"ptType"},{"type":"text","text":" of GPX schema. Not supported in GPXRoot, nor GPXParser’s parsing."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxpoint"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/coregpx\/gpxpoint"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSObject","doc:\/\/org.cocoapods.CoreGPX\/s7CVarArgP","doc:\/\/org.cocoapods.CoreGPX\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.CoreGPX\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.CoreGPX\/Se","doc:\/\/org.cocoapods.CoreGPX\/SE","doc:\/\/org.cocoapods.CoreGPX\/SQ","doc:\/\/org.cocoapods.CoreGPX\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This class ("},{"type":"codeVoice","code":"ptType"},{"type":"text","text":") is added to conform with the GPX v1.1 schema."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXPoint"}],"title":"GPXPoint","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CoreGPX@objc(cs)GPXPoint","modules":[{"name":"CoreGPX"}],"navigatorTitle":[{"kind":"identifier","text":"GPXPoint"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint\/init()","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint\/init(from:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint\/init(latitude:longitude:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint\/elevation","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint\/latitude","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint\/longitude","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint\/time"]}],"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXPoint/longitude":{"role":"symbol","title":"longitude","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"longitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Longitude of point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint\/longitude","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxpoint\/longitude"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXElement":{"role":"symbol","title":"GPXElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXElement"}],"abstract":[{"type":"text","text":"A root class for all element types"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXElement"}],"url":"\/documentation\/coregpx\/gpxelement"},"doc://org.cocoapods.CoreGPX/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SQ"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXPoint/latitude":{"role":"symbol","title":"latitude","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Latitude of point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint\/latitude","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxpoint\/latitude"},"doc://org.cocoapods.CoreGPX/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSObject"},"doc://org.cocoapods.CoreGPX/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/Se"},"doc://org.cocoapods.CoreGPX/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SH"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXPoint/elevation":{"role":"symbol","title":"elevation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"elevation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Elevation Value in (metre, m)"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint\/elevation","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxpoint\/elevation"},"doc://org.cocoapods.CoreGPX/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.CoreGPX/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s23CustomStringConvertibleP"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXPoint/init(latitude:longitude:)":{"role":"symbol","title":"init(latitude:longitude:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"longitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize with latitude and longitude"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint\/init(latitude:longitude:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxpoint\/init(latitude:longitude:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXPoint":{"role":"symbol","title":"GPXPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXPoint"}],"abstract":[{"type":"text","text":"This class ("},{"type":"codeVoice","code":"ptType"},{"type":"text","text":") is added to conform with the GPX v1.1 schema."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXPoint"}],"url":"\/documentation\/coregpx\/gpxpoint"},"doc://org.cocoapods.CoreGPX/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SE"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXPoint/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Default Initializer."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/coregpx\/gpxpoint\/init()"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXPoint/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxpoint\/init(from:)"},"doc://org.cocoapods.CoreGPX/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s7CVarArgP"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXPoint/time":{"role":"symbol","title":"time","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Time\/Date of creation"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint\/time","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxpoint\/time"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GPXPoint"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GPXPoint"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GPXPoint"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPoint\/init()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXPoint"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXElement","text":"GPXElement"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/title","value":"GPXElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/fragments","value":[{"kind":"identifier","text":"GPXElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPoint\/title","value":"GPXPoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPoint\/fragments","value":[{"kind":"identifier","text":"GPXPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPoint~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPoint~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}