{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXParser"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This parser is already setted up, hence, does not require any handling, and will parse files directly as objects."},{"type":"text","text":" "},{"type":"text","text":"To get the parsed data from a GPX file, simply initialize the parser, and get the "},{"type":"codeVoice","code":"GPXRoot"},{"type":"text","text":" from "},{"type":"codeVoice","code":"parsedData()"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxparser"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/coregpx\/gpxparser"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSXMLParserDelegate","doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSObject","doc:\/\/org.cocoapods.CoreGPX\/s7CVarArgP","doc:\/\/org.cocoapods.CoreGPX\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.CoreGPX\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.CoreGPX\/SQ","doc:\/\/org.cocoapods.CoreGPX\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An event-driven parser (SAX parser), currently parses GPX v1.1 files only."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXParser"}],"title":"GPXParser","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CoreGPX@objc(cs)GPXParser","modules":[{"name":"CoreGPX"}],"navigatorTitle":[{"kind":"identifier","text":"GPXParser"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/init(withData:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/init(withPath:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/init(withRawString:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/init(withStream:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/init(withURL:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/fallibleParsedData(forceContinue:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/legacyParsingData()","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/lossyParsing(type:affecting:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/parsedData()"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/XMLParserDelegate-Implementations"],"generated":true}],"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser/legacyParsingData()":{"role":"symbol","title":"legacyParsingData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"legacyParsingData"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GPXLegacyRoot","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLegacyRoot"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Starts parsing, returns parsed "},{"type":"codeVoice","code":"GPXRoot"},{"type":"text","text":" when done."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/legacyParsingData()","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxparser\/legacyparsingdata()"},"doc://org.cocoapods.CoreGPX/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.CoreGPX\/objc(cs)NSObject"},"doc://org.cocoapods.CoreGPX/objc(pl)NSXMLParserDelegate":{"type":"unresolvable","title":"Foundation.XMLParserDelegate","identifier":"doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSXMLParserDelegate"},"doc://org.cocoapods.CoreGPX/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s23CustomStringConvertibleP"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser/lossyParsing(type:affecting:)":{"role":"symbol","title":"lossyParsing(type:affecting:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lossyParsing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXCompression","preciseIdentifier":"s:7CoreGPX14GPXCompressionC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"lossyTypes","preciseIdentifier":"s:7CoreGPX14GPXCompressionC10lossyTypesO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"affecting"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXCompression","preciseIdentifier":"s:7CoreGPX14GPXCompressionC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"lossyOptions","preciseIdentifier":"s:7CoreGPX14GPXCompressionC12lossyOptionsO"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"GPXRoot","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXRoot"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Parse GPX file, while lossy compressing it straight away, post-parsing."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/lossyParsing(type:affecting:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxparser\/lossyparsing(type:affecting:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser":{"role":"symbol","title":"GPXParser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXParser"}],"abstract":[{"type":"text","text":"An event-driven parser (SAX parser), currently parses GPX v1.1 files only."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXParser"}],"url":"\/documentation\/coregpx\/gpxparser"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser/init(withPath:)":{"role":"symbol","title":"init(withPath:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"withPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"for parsing with a path to a GPX file"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/init(withPath:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxparser\/init(withpath:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser/init(withURL:)":{"role":"symbol","title":"init(withURL:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"withURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"for parsing with "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" type"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/init(withURL:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxparser\/init(withurl:)"},"doc://org.cocoapods.CoreGPX/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSObject"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser/XMLParserDelegate-Implementations":{"role":"collectionGroup","title":"XMLParserDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/XMLParserDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/coregpx\/gpxparser\/xmlparserdelegate-implementations"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser/fallibleParsedData(forceContinue:)":{"role":"symbol","title":"fallibleParsedData(forceContinue:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fallibleParsedData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forceContinue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"GPXRoot","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXRoot"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Starts parsing, returns parsed "},{"type":"codeVoice","code":"GPXRoot"},{"type":"text","text":" when done."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/fallibleParsedData(forceContinue:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxparser\/fallibleparseddata(forcecontinue:)"},"doc://org.cocoapods.CoreGPX/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SH"},"doc://org.cocoapods.CoreGPX/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s7CVarArgP"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser/init(withRawString:)":{"role":"symbol","title":"init(withRawString:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"withRawString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"for parsing with a string that contains full GPX markup"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/init(withRawString:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxparser\/init(withrawstring:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser/init(withData:)":{"role":"symbol","title":"init(withData:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"for parsing with "},{"type":"codeVoice","code":"Data"},{"type":"text","text":" type"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/init(withData:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxparser\/init(withdata:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser/parsedData()":{"role":"symbol","title":"parsedData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parsedData"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GPXRoot","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXRoot"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Starts parsing, returns parsed "},{"type":"codeVoice","code":"GPXRoot"},{"type":"text","text":" when done."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/parsedData()","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxparser\/parseddata()"},"doc://org.cocoapods.CoreGPX/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.CoreGPX/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SQ"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXParser/init(withStream:)":{"role":"symbol","title":"init(withStream:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withStream"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InputStream","preciseIdentifier":"c:objc(cs)NSInputStream"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"for parsing with "},{"type":"codeVoice","code":"InputStream"},{"type":"text","text":" type"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/init(withStream:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxparser\/init(withstream:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GPXParser"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GPXParser"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GPXParser"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXParser\/XMLParserDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXParser"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser\/title","value":"GPXParser"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXParser\/fragments","value":[{"kind":"identifier","text":"GPXParser"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}