{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRouteType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxroutetype"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoute","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoute"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRouteType","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRouteType\/comment","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRouteType\/desc","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRouteType\/name","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRouteType\/number","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRouteType\/source"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRouteType"}],"title":"GPXRouteType","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:7CoreGPX12GPXRouteTypeP","modules":[{"name":"CoreGPX"}],"navigatorTitle":[{"kind":"identifier","text":"GPXRouteType"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoute":{"role":"symbol","title":"GPXLegacyRoute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyRoute"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyRoute"}],"url":"\/documentation\/coregpx\/gpxlegacyroute"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRouteType/comment":{"role":"symbol","title":"comment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"comment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Additional comment of the route."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRouteType\/comment","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coregpx\/gpxroutetype\/comment"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRouteType":{"role":"symbol","title":"GPXRouteType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRouteType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRouteType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRouteType"}],"url":"\/documentation\/coregpx\/gpxroutetype"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRouteType/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Name of the route."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRouteType\/name","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coregpx\/gpxroutetype\/name"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRouteType/source":{"role":"symbol","title":"source","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Source of the route."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRouteType\/source","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coregpx\/gpxroutetype\/source"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoute":{"role":"symbol","title":"GPXRoute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRoute"}],"abstract":[{"type":"text","text":"Value type that represents a route, or "},{"type":"codeVoice","code":"rteType"},{"type":"text","text":" in GPX v1.1 schema."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRoute"}],"url":"\/documentation\/coregpx\/gpxroute"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRouteType/desc":{"role":"symbol","title":"desc","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"desc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Description of the route."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRouteType\/desc","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coregpx\/gpxroutetype\/desc"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRouteType/number":{"role":"symbol","title":"number","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"number"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Number of route (possibly a tag for the route)"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRouteType\/number","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coregpx\/gpxroutetype\/number"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoute\/title","value":"GPXLegacyRoute"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoute\/fragments","value":[{"kind":"identifier","text":"GPXLegacyRoute"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoute\/title","value":"GPXRoute"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoute\/fragments","value":[{"kind":"identifier","text":"GPXRoute"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}