{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRootElement"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXElement","text":"GPXElement"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxrootelement"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRootElement","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRootElement\/creator","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRootElement\/version"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRootElement"}],"title":"GPXRootElement","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:7CoreGPX14GPXRootElementP","modules":[{"name":"CoreGPX"}],"navigatorTitle":[{"kind":"identifier","text":"GPXRootElement"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRootElement/version":{"role":"symbol","title":"version","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"version"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXVersion","preciseIdentifier":"s:7CoreGPX10GPXVersionO"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRootElement\/version","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coregpx\/gpxrootelement\/version"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRootElement":{"role":"symbol","title":"GPXRootElement","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRootElement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRootElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRootElement"}],"url":"\/documentation\/coregpx\/gpxrootelement"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXElement":{"role":"symbol","title":"GPXElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXElement"}],"abstract":[{"type":"text","text":"A root class for all element types"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXElement"}],"url":"\/documentation\/coregpx\/gpxelement"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRootElement/creator":{"role":"symbol","title":"creator","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"creator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRootElement\/creator","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coregpx\/gpxrootelement\/creator"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoot":{"role":"symbol","title":"GPXLegacyRoot","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyRoot"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoot","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyRoot"}],"url":"\/documentation\/coregpx\/gpxlegacyroot"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/title","value":"GPXElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/fragments","value":[{"kind":"identifier","text":"GPXElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoot\/title","value":"GPXLegacyRoot"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoot\/fragments","value":[{"kind":"identifier","text":"GPXLegacyRoot"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}