{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRoot"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"GPXRoot"},{"type":"text","text":" holds all "},{"type":"codeVoice","code":"metadata"},{"type":"text","text":", "},{"type":"codeVoice","code":"waypoints"},{"type":"text","text":", "},{"type":"codeVoice","code":"tracks"},{"type":"text","text":", "},{"type":"codeVoice","code":"routes"},{"type":"text","text":" and "},{"type":"codeVoice","code":"extensions"},{"type":"text","text":" types together before being packaged as a GPX file, or formatted as per GPX schema’s requirements."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxroot"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/coregpx\/gpxroot"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSObject","doc:\/\/org.cocoapods.CoreGPX\/s7CVarArgP","doc:\/\/org.cocoapods.CoreGPX\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.CoreGPX\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.CoreGPX\/Se","doc:\/\/org.cocoapods.CoreGPX\/SE","doc:\/\/org.cocoapods.CoreGPX\/SQ","doc:\/\/org.cocoapods.CoreGPX\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creation of a GPX file or GPX formatted string starts here"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRoot"}],"title":"GPXRoot","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CoreGPX@objc(cs)GPXRoot","modules":[{"name":"CoreGPX"}],"navigatorTitle":[{"kind":"identifier","text":"GPXRoot"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/init()","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/init(creator:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/init(from:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/init(withExtensionAttributes:schemaLocation:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/init(withExtensionAttributes:schemaLocation:creator:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/creator","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/extensions","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/metadata","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/routes","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/tracks","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/version","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/waypoints"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/add(route:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/add(routes:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/add(track:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/add(tracks:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/add(waypoint:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/add(waypoints:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/newRoute()","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/newTrack()","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/newWaypointWith(latitude:longitude:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/outputToFile(saveAt:fileName:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/remove(WaypointAtIndex:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/remove(route:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/remove(track:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/remove(waypoint:)"]}],"references":{"doc://org.cocoapods.CoreGPX/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/creator":{"role":"symbol","title":"creator","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"creator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Name of the creator of the GPX content."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/creator","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/creator"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXElement":{"role":"symbol","title":"GPXElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXElement"}],"abstract":[{"type":"text","text":"A root class for all element types"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXElement"}],"url":"\/documentation\/coregpx\/gpxelement"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/routes":{"role":"symbol","title":"routes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXRoute","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXRoute"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Array of routes"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/routes","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/routes"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/add(tracks:)":{"role":"symbol","title":"add(tracks:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tracks"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXTrack","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrack"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Add an array of pre-initialized and configured tracks to "},{"type":"codeVoice","code":"GPXRoot"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/add(tracks:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/add(tracks:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"for initializing without a creator name"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/coregpx\/gpxroot\/init()"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/remove(route:)":{"role":"symbol","title":"remove(route:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"route"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXRoute","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXRoute"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Removes an already added waypoint from "},{"type":"codeVoice","code":"GPXRoot"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/remove(route:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/remove(route:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/metadata":{"role":"symbol","title":"metadata","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXMetadata","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXMetadata"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Metadata to be included in your GPX content."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/metadata","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/metadata"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/init(from:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/newWaypointWith(latitude:longitude:)":{"role":"symbol","title":"newWaypointWith(latitude:longitude:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newWaypointWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"longitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GPXWaypoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXWaypoint"}],"abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"waypoint"},{"type":"text","text":" which is also added to "},{"type":"codeVoice","code":"GPXRoot"},{"type":"text","text":" automatically"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/newWaypointWith(latitude:longitude:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/newwaypointwith(latitude:longitude:)"},"doc://org.cocoapods.CoreGPX/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSObject"},"doc://org.cocoapods.CoreGPX/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SH"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/add(waypoints:)":{"role":"symbol","title":"add(waypoints:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"waypoints"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXWaypoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXWaypoint"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Add an array of pre-initialized and configured waypoints to "},{"type":"codeVoice","code":"GPXRoot"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/add(waypoints:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/add(waypoints:)"},"doc://org.cocoapods.CoreGPX/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/Se"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/init(creator:)":{"role":"symbol","title":"init(creator:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"creator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"for initializing with a creator name"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/init(creator:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/init(creator:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/extensions":{"role":"symbol","title":"extensions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extensions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXExtensions","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXExtensions"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Items for extensions to GPX schema (if any)"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/extensions","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/extensions"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/add(track:)":{"role":"symbol","title":"add(track:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"track"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXTrack","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrack"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Add a pre-initialized and configured track to "},{"type":"codeVoice","code":"GPXRoot"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/add(track:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/add(track:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/init(withExtensionAttributes:schemaLocation:creator:)":{"role":"symbol","title":"init(withExtensionAttributes:schemaLocation:creator:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withExtensionAttributes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"schemaLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"creator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize if planned to use with extensions, with creator name."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/init(withExtensionAttributes:schemaLocation:creator:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/init(withextensionattributes:schemalocation:creator:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/outputToFile(saveAt:fileName:)":{"role":"symbol","title":"outputToFile(saveAt:fileName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputToFile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"saveAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fileName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"for saving newly tracked data straight to a GPX file in a directory"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/outputToFile(saveAt:fileName:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/outputtofile(saveat:filename:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/init(withExtensionAttributes:schemaLocation:)":{"role":"symbol","title":"init(withExtensionAttributes:schemaLocation:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withExtensionAttributes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"schemaLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize if planned to use with extensions"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/init(withExtensionAttributes:schemaLocation:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/init(withextensionattributes:schemalocation:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/add(waypoint:)":{"role":"symbol","title":"add(waypoint:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"waypoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXWaypoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXWaypoint"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Add a pre-initialized and configured waypoint to "},{"type":"codeVoice","code":"GPXRoot"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/add(waypoint:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/add(waypoint:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/newTrack()":{"role":"symbol","title":"newTrack()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newTrack"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GPXTrack","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrack"}],"abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"track"},{"type":"text","text":" which is also added to "},{"type":"codeVoice","code":"GPXRoot"},{"type":"text","text":" automatically"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/newTrack()","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/newtrack()"},"doc://org.cocoapods.CoreGPX/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s7CVarArgP"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/waypoints":{"role":"symbol","title":"waypoints","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"waypoints"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXWaypoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXWaypoint"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Array of waypoints"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/waypoints","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/waypoints"},"doc://org.cocoapods.CoreGPX/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s23CustomStringConvertibleP"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/remove(WaypointAtIndex:)":{"role":"symbol","title":"remove(WaypointAtIndex:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"WaypointAtIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Remove waypoint from root’s array at index."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/remove(WaypointAtIndex:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/remove(waypointatindex:)"},"doc://org.cocoapods.CoreGPX/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SE"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/newRoute()":{"role":"symbol","title":"newRoute()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newRoute"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GPXRoute","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXRoute"}],"abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"route"},{"type":"text","text":" which is also added to "},{"type":"codeVoice","code":"GPXRoot"},{"type":"text","text":" automatically"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/newRoute()","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/newroute()"},"doc://org.cocoapods.CoreGPX/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SQ"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/tracks":{"role":"symbol","title":"tracks","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tracks"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXTrack","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrack"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Array of tracks"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/tracks","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/tracks"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/remove(track:)":{"role":"symbol","title":"remove(track:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"track"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXTrack","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrack"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Removes an already added track from "},{"type":"codeVoice","code":"GPXRoot"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/remove(track:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/remove(track:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/remove(waypoint:)":{"role":"symbol","title":"remove(waypoint:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"waypoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXWaypoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXWaypoint"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Removes an already added waypoint from "},{"type":"codeVoice","code":"GPXRoot"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/remove(waypoint:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/remove(waypoint:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/version":{"role":"symbol","title":"version","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"version"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"GPX version that will be generated."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/version","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/version"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/add(routes:)":{"role":"symbol","title":"add(routes:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"routes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXRoute","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXRoute"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Add an array of pre-initialized and configured routes to "},{"type":"codeVoice","code":"GPXRoot"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/add(routes:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/add(routes:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot/add(route:)":{"role":"symbol","title":"add(route:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"route"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXRoute","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXRoute"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Add a pre-initialized and configured route to "},{"type":"codeVoice","code":"GPXRoot"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/add(route:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxroot\/add(route:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoot":{"role":"symbol","title":"GPXRoot","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRoot"}],"abstract":[{"type":"text","text":"Creation of a GPX file or GPX formatted string starts here"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRoot"}],"url":"\/documentation\/coregpx\/gpxroot"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GPXRoot"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GPXRoot"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GPXRoot"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoot\/init()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRoot"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXElement","text":"GPXElement"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/title","value":"GPXElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/fragments","value":[{"kind":"identifier","text":"GPXElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoot~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoot~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoot\/title","value":"GPXRoot"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoot\/fragments","value":[{"kind":"identifier","text":"GPXRoot"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}