{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrackSegment"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Does not hold additional information by default."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxtracksegment"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/coregpx\/gpxtracksegment"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSObject","doc:\/\/org.cocoapods.CoreGPX\/s7CVarArgP","doc:\/\/org.cocoapods.CoreGPX\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.CoreGPX\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.CoreGPX\/Se","doc:\/\/org.cocoapods.CoreGPX\/SE","doc:\/\/org.cocoapods.CoreGPX\/SQ","doc:\/\/org.cocoapods.CoreGPX\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A track segment that holds data on all track points in the particular segment."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrackSegment"}],"title":"GPXTrackSegment","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CoreGPX@objc(cs)GPXTrackSegment","modules":[{"name":"CoreGPX"}],"navigatorTitle":[{"kind":"identifier","text":"GPXTrackSegment"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/init()","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/extensions","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/points","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/trackpoints"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/add(trackpoint:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/add(trackpoints:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/newTrackpointWith(latitude:longitude:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/remove(trackpoint:)"]}],"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrackSegment/trackpoints":{"role":"symbol","title":"trackpoints","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackpoints"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXTrackPoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackPoint"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Track points stored in current segment."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/trackpoints","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/coregpx\/gpxtracksegment\/trackpoints"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrackSegment/newTrackpointWith(latitude:longitude:)":{"role":"symbol","title":"newTrackpointWith(latitude:longitude:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newTrackpointWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"longitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GPXTrackPoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackPoint"}],"abstract":[{"type":"text","text":"Initializes a new trackpoint to segment, and returns the trackpoint."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/newTrackpointWith(latitude:longitude:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtracksegment\/newtrackpointwith(latitude:longitude:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrackSegment/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Default Initializer."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/coregpx\/gpxtracksegment\/init()"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrackSegment/add(trackpoint:)":{"role":"symbol","title":"add(trackpoint:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackpoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXTrackPoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackPoint"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Adds a single track point to this track segment."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/add(trackpoint:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtracksegment\/add(trackpoint:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrackSegment/add(trackpoints:)":{"role":"symbol","title":"add(trackpoints:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackpoints"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXTrackPoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackPoint"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Adds an array of track points to this track segment."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/add(trackpoints:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtracksegment\/add(trackpoints:)"},"doc://org.cocoapods.CoreGPX/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s23CustomStringConvertibleP"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrackSegment/remove(trackpoint:)":{"role":"symbol","title":"remove(trackpoint:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackpoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXTrackPoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackPoint"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Removes a track point from this track segment."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/remove(trackpoint:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtracksegment\/remove(trackpoint:)"},"doc://org.cocoapods.CoreGPX/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SE"},"doc://org.cocoapods.CoreGPX/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSObject"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrackSegment/extensions":{"role":"symbol","title":"extensions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extensions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXExtensions","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXExtensions"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Custom Extensions, if needed."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/extensions","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtracksegment\/extensions"},"doc://org.cocoapods.CoreGPX/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SH"},"doc://org.cocoapods.CoreGPX/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s7CVarArgP"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXElement":{"role":"symbol","title":"GPXElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXElement"}],"abstract":[{"type":"text","text":"A root class for all element types"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXElement"}],"url":"\/documentation\/coregpx\/gpxelement"},"doc://org.cocoapods.CoreGPX/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/Se"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrackSegment/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtracksegment\/init(from:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrackSegment/points":{"role":"symbol","title":"points","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"points"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXTrackPoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackPoint"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Track points stored in current segment."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/points","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtracksegment\/points"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrackSegment":{"role":"symbol","title":"GPXTrackSegment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrackSegment"}],"abstract":[{"type":"text","text":"A track segment that holds data on all track points in the particular segment."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXTrackSegment"}],"url":"\/documentation\/coregpx\/gpxtracksegment"},"doc://org.cocoapods.CoreGPX/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SQ"},"doc://org.cocoapods.CoreGPX/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GPXTrackSegment"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GPXTrackSegment"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GPXTrackSegment"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment\/init()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrackSegment"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXElement","text":"GPXElement"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackSegment~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackSegment~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/title","value":"GPXElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/fragments","value":[{"kind":"identifier","text":"GPXElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackSegment\/title","value":"GPXTrackSegment"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackSegment\/fragments","value":[{"kind":"identifier","text":"GPXTrackSegment"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}