{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrack"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A track can hold track segments, along with additional information regarding the track."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Tracks are meant to show the start and finish of a journey, through the track segments that it holds."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxtrack"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/coregpx\/gpxtrack"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSObject","doc:\/\/org.cocoapods.CoreGPX\/s7CVarArgP","doc:\/\/org.cocoapods.CoreGPX\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.CoreGPX\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.CoreGPX\/Se","doc:\/\/org.cocoapods.CoreGPX\/SE","doc:\/\/org.cocoapods.CoreGPX\/SQ","doc:\/\/org.cocoapods.CoreGPX\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents "},{"type":"codeVoice","code":"trkType"},{"type":"text","text":" of GPX v1.1 schema."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrack"}],"title":"GPXTrack","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CoreGPX@objc(cs)GPXTrack","modules":[{"name":"CoreGPX"}],"navigatorTitle":[{"kind":"identifier","text":"GPXTrack"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/init()","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/comment","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/desc","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/extensions","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/link","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/links","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/name","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/number","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/segments","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/source","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/tracksegments","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/add(trackSegment:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/add(trackSegments:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/newLink(withHref:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/newTrackPointWith(latitude:longitude:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/newTrackSegment()","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/remove(trackSegment:)"]}],"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXElement":{"role":"symbol","title":"GPXElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXElement"}],"abstract":[{"type":"text","text":"A root class for all element types"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXElement"}],"url":"\/documentation\/coregpx\/gpxelement"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Name of track."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/name","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtrack\/name"},"doc://org.cocoapods.CoreGPX/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/Se"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/links":{"role":"symbol","title":"links","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"links"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXLink","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLink"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"A value type for link properties (see "},{"type":"codeVoice","code":"GPXLink"},{"type":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/links","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtrack\/links"},"doc://org.cocoapods.CoreGPX/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s7CVarArgP"},"doc://org.cocoapods.CoreGPX/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSObject"},"doc://org.cocoapods.CoreGPX/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SQ"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/source":{"role":"symbol","title":"source","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Source of track."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/source","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtrack\/source"},"doc://org.cocoapods.CoreGPX/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s23CustomStringConvertibleP"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/extensions":{"role":"symbol","title":"extensions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extensions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXExtensions","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXExtensions"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Custom Extensions of track, if needed."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/extensions","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtrack\/extensions"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/tracksegments":{"role":"symbol","title":"tracksegments","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tracksegments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXTrackSegment","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackSegment"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Array of track segments. Must be included in every track."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/tracksegments","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/coregpx\/gpxtrack\/tracksegments"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Type of current track."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/type","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtrack\/type"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack":{"role":"symbol","title":"GPXTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrack"}],"abstract":[{"type":"text","text":"Represents "},{"type":"codeVoice","code":"trkType"},{"type":"text","text":" of GPX v1.1 schema."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXTrack"}],"url":"\/documentation\/coregpx\/gpxtrack"},"doc://org.cocoapods.CoreGPX/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.CoreGPX/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SH"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/add(trackSegments:)":{"role":"symbol","title":"add(trackSegments:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackSegments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXTrackSegment","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackSegment"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Adds an array of track segments to the track."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/add(trackSegments:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtrack\/add(tracksegments:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Default Initializer"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/coregpx\/gpxtrack\/init()"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/newTrackPointWith(latitude:longitude:)":{"role":"symbol","title":"newTrackPointWith(latitude:longitude:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newTrackPointWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"longitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GPXTrackPoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackPoint"}],"abstract":[{"type":"text","text":"Initializes a new track point in track, then returns the new track point."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/newTrackPointWith(latitude:longitude:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtrack\/newtrackpointwith(latitude:longitude:)"},"doc://org.cocoapods.CoreGPX/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SE"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/link":{"role":"symbol","title":"link","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"link"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXLink","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLink"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A value type for link properties (see "},{"type":"codeVoice","code":"GPXLink"},{"type":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/link","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/coregpx\/gpxtrack\/link"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/number":{"role":"symbol","title":"number","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"number"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"GPS track number."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/number","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtrack\/number"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/add(trackSegment:)":{"role":"symbol","title":"add(trackSegment:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackSegment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXTrackSegment","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackSegment"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Adds a single track segment to the track."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/add(trackSegment:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtrack\/add(tracksegment:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/segments":{"role":"symbol","title":"segments","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"segments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXTrackSegment","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackSegment"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Array of track segments. Must be included in every track."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/segments","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtrack\/segments"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtrack\/init(from:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/comment":{"role":"symbol","title":"comment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"comment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Additional comment of track."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/comment","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtrack\/comment"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/newTrackSegment()":{"role":"symbol","title":"newTrackSegment()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newTrackSegment"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GPXTrackSegment","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackSegment"}],"abstract":[{"type":"text","text":"Initialize a new "},{"type":"codeVoice","code":"GPXTrackSegement"},{"type":"text","text":" to the track."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/newTrackSegment()","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtrack\/newtracksegment()"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/newLink(withHref:)":{"role":"symbol","title":"newLink(withHref:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newLink"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withHref"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GPXLink","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLink"}],"abstract":[{"type":"text","text":"Initialize a new "},{"type":"codeVoice","code":"GPXLink"},{"type":"text","text":" to the track."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/newLink(withHref:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtrack\/newlink(withhref:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/desc":{"role":"symbol","title":"desc","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"desc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A full description of the track. Can be of any length."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/desc","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtrack\/desc"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/remove(trackSegment:)":{"role":"symbol","title":"remove(trackSegment:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackSegment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXTrackSegment","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackSegment"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Removes a tracksegment from the track."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/remove(trackSegment:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtrack\/remove(tracksegment:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GPXTrack"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GPXTrack"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GPXTrack"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/init()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrack"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXElement","text":"GPXElement"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/title","value":"GPXElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/fragments","value":[{"kind":"identifier","text":"GPXElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrack\/title","value":"GPXTrack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrack\/fragments","value":[{"kind":"identifier","text":"GPXTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrack~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrack~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}