{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXWaypoint"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"According to the GPX schema, the waypoint type can represent the following:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"a waypoint"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"a point of interest"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"a named feature on a map"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The waypoint should at least contain the attributes of both "},{"type":"codeVoice","code":"latitude"},{"type":"text","text":" and "},{"type":"codeVoice","code":"longitude"},{"type":"text","text":" in order to be considered a valid waypoint. Most attributes are optional, and are not required to be implemented."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxwaypoint"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/coregpx\/gpxwaypoint"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoutePoint","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackPoint"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypointProtocol","doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSObject","doc:\/\/org.cocoapods.CoreGPX\/s7CVarArgP","doc:\/\/org.cocoapods.CoreGPX\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.CoreGPX\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.CoreGPX\/Se","doc:\/\/org.cocoapods.CoreGPX\/SE","doc:\/\/org.cocoapods.CoreGPX\/SQ","doc:\/\/org.cocoapods.CoreGPX\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A value type that represents waypoint based off GPX v1.1 schema’s "},{"type":"codeVoice","code":"wptType"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXWaypoint"}],"title":"GPXWaypoint","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CoreGPX@objc(cs)GPXWaypoint","modules":[{"name":"CoreGPX"}],"navigatorTitle":[{"kind":"identifier","text":"GPXWaypoint"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/init()","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/init(from:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/init(latitude:longitude:)","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/init(verifiedLatitude:longitude:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/DGPSid","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/ageofDGPSData","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/comment","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/desc","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/elevation","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/extensions","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/fix","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/geoidHeight","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/horizontalDilution","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/latitude","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/link","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/links","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/longitude","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/magneticVariation","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/name","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/positionDilution","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/satellites","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/source","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/symbol","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/time","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/type","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/verticalDilution"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/newLink(withHref:)"]}],"references":{"doc://org.cocoapods.CoreGPX/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/link":{"role":"symbol","title":"link","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"link"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXLink","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLink"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A value type for link properties (see "},{"type":"codeVoice","code":"GPXLink"},{"type":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/link","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/coregpx\/gpxwaypoint\/link"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/init(verifiedLatitude:longitude:)":{"role":"symbol","title":"init(verifiedLatitude:longitude:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"verifiedLatitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"longitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Initialize a point type, and verifies that point is within ranges of what latitude and longitude should be."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/init(verifiedLatitude:longitude:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/init(verifiedlatitude:longitude:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/horizontalDilution":{"role":"symbol","title":"horizontalDilution","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"horizontalDilution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Horizontal dilution of precision of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/horizontalDilution","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/horizontaldilution"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Name of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/name","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/name"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/comment":{"role":"symbol","title":"comment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"comment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Comment of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/comment","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/comment"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXElement":{"role":"symbol","title":"GPXElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXElement"}],"abstract":[{"type":"text","text":"A root class for all element types"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXElement"}],"url":"\/documentation\/coregpx\/gpxelement"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/init(from:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/DGPSid":{"role":"symbol","title":"DGPSid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"DGPSid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"DGPS’ ID"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/DGPSid","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/dgpsid"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/longitude":{"role":"symbol","title":"longitude","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"longitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Longitude of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/longitude","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/longitude"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/init(latitude:longitude:)":{"role":"symbol","title":"init(latitude:longitude:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"longitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize with current date and time, with latitude and longitude."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/init(latitude:longitude:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/init(latitude:longitude:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/ageofDGPSData":{"role":"symbol","title":"ageofDGPSData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ageofDGPSData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Age of DGPS Data"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/ageofDGPSData","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/ageofdgpsdata"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypointProtocol":{"role":"symbol","title":"GPXWaypointProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXWaypointProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypointProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXWaypointProtocol"}],"url":"\/documentation\/coregpx\/gpxwaypointprotocol"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/geoidHeight":{"role":"symbol","title":"geoidHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"geoidHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Geoid Height of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/geoidHeight","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/geoidheight"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/satellites":{"role":"symbol","title":"satellites","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"satellites"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Number of satellites used to calculate GPS fix of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/satellites","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/satellites"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/elevation":{"role":"symbol","title":"elevation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"elevation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Elevation of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/elevation","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/elevation"},"doc://org.cocoapods.CoreGPX/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.CoreGPX\/objc(pl)NSObject"},"doc://org.cocoapods.CoreGPX/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SH"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/newLink(withHref:)":{"role":"symbol","title":"newLink(withHref:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newLink"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withHref"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GPXLink","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLink"}],"abstract":[{"type":"text","text":"for initializing a "},{"type":"codeVoice","code":"GPXLink"},{"type":"text","text":" with href, which is added to this point type as well."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/newLink(withHref:)","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/coregpx\/gpxwaypoint\/newlink(withhref:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/latitude":{"role":"symbol","title":"latitude","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Latitude of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/latitude","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/latitude"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/fix":{"role":"symbol","title":"fix","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fix"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXFix","preciseIdentifier":"s:7CoreGPX6GPXFixO"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Type of GPS fix of current point, represented as a number"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/fix","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/fix"},"doc://org.cocoapods.CoreGPX/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/Se"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/extensions":{"role":"symbol","title":"extensions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extensions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXExtensions","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXExtensions"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Extension to GPX v1.1 standard."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/extensions","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/extensions"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrackPoint":{"role":"symbol","title":"GPXTrackPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrackPoint"}],"abstract":[{"type":"text","text":"A track point is just like a waypoint or route point, but is suited to be part of a track segment."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackPoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXTrackPoint"}],"url":"\/documentation\/coregpx\/gpxtrackpoint"},"doc://org.cocoapods.CoreGPX/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s7CVarArgP"},"doc://org.cocoapods.CoreGPX/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SE"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/time":{"role":"symbol","title":"time","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Date and time of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/time","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/time"},"doc://org.cocoapods.CoreGPX/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreGPX\/s23CustomStringConvertibleP"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/desc":{"role":"symbol","title":"desc","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"desc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Description of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/desc","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/desc"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/verticalDilution":{"role":"symbol","title":"verticalDilution","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"verticalDilution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Vertical dilution of precision of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/verticalDilution","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/verticaldilution"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/links":{"role":"symbol","title":"links","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"links"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXLink","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLink"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"A value type for link properties (see "},{"type":"codeVoice","code":"GPXLink"},{"type":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/links","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/links"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/magneticVariation":{"role":"symbol","title":"magneticVariation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"magneticVariation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Magnetic Variation of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/magneticVariation","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/magneticvariation"},"doc://org.cocoapods.CoreGPX/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.CoreGPX\/SQ"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoutePoint":{"role":"symbol","title":"GPXRoutePoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRoutePoint"}],"abstract":[{"type":"text","text":"A route point is just like a waypoint or track point, but is suited to be part of a route."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoutePoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRoutePoint"}],"url":"\/documentation\/coregpx\/gpxroutepoint"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/source":{"role":"symbol","title":"source","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Source of data of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/source","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/source"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Initialize with current date and time"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/coregpx\/gpxwaypoint\/init()"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/symbol":{"role":"symbol","title":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"symbol"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Text of GPS symbol name"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/symbol","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/symbol"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Type of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/type","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/type"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/positionDilution":{"role":"symbol","title":"positionDilution","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"positionDilution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Position dilution of precision of current point"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/positionDilution","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/positiondilution"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint":{"role":"symbol","title":"GPXWaypoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXWaypoint"}],"abstract":[{"type":"text","text":"A value type that represents waypoint based off GPX v1.1 schema’s "},{"type":"codeVoice","code":"wptType"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXWaypoint"}],"url":"\/documentation\/coregpx\/gpxwaypoint"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GPXWaypoint"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GPXWaypoint"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GPXWaypoint"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/init()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoutePoint","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackPoint"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXWaypoint"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXElement","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXElement","text":"GPXElement"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/title","value":"GPXElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXElement\/fragments","value":[{"kind":"identifier","text":"GPXElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackPoint\/title","value":"GPXTrackPoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackPoint\/fragments","value":[{"kind":"identifier","text":"GPXTrackPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoutePoint\/title","value":"GPXRoutePoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoutePoint\/fragments","value":[{"kind":"identifier","text":"GPXRoutePoint"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXWaypoint~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXWaypoint~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXWaypoint\/title","value":"GPXWaypoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXWaypoint\/fragments","value":[{"kind":"identifier","text":"GPXWaypoint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}