{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadTile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":" "},{"kind":"internalParam","text":"path"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKTileOverlayPath","preciseIdentifier":"c:@SA@MKTileOverlayPath"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapcache\/cachedtileoverlay\/loadtile(at:result:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapcache\/cachedtileoverlay\/loadtile(at:result:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay\/loadTile(at:result:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"When invoked it will load the tile using the standard OS implementation (if "},{"type":"codeVoice","code":"useCache"},{"type":"text","text":"is "},{"type":"codeVoice","code":"false"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"or from the cache (if "},{"type":"codeVoice","code":"useCache"},{"type":"text","text":" is "},{"type":"codeVoice","code":"true"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadTile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKTileOverlayPath","preciseIdentifier":"c:@SA@MKTileOverlayPath"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"loadTile(at:result:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@MapCache@objc(cs)CachedTileOverlay(im)loadTileAtPath:result:","modules":[{"name":"MapCache"}],"navigatorTitle":[{"kind":"identifier","text":"loadTileAtPath:result:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay"]]},"references":{"doc://org.cocoapods.MapCache/documentation/MapCache/CachedTileOverlay/loadTile(at:result:)":{"role":"symbol","title":"loadTile(at:result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadTile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKTileOverlayPath","preciseIdentifier":"c:@SA@MKTileOverlayPath"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When invoked it will load the tile using the standard OS implementation (if "},{"type":"codeVoice","code":"useCache"},{"type":"text","text":"is "},{"type":"codeVoice","code":"false"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"or from the cache (if "},{"type":"codeVoice","code":"useCache"},{"type":"text","text":" is "},{"type":"codeVoice","code":"true"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay\/loadTile(at:result:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadTileAtPath:result:"}],"url":"\/documentation\/mapcache\/cachedtileoverlay\/loadtile(at:result:)"},"doc://org.cocoapods.MapCache/documentation/MapCache/CachedTileOverlay":{"role":"symbol","title":"CachedTileOverlay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CachedTileOverlay"}],"abstract":[{"type":"text","text":"Whenever a tile is requested by the "},{"type":"codeVoice","code":"MapView"},{"type":"text","text":", it calls the "},{"type":"codeVoice","code":"MKTileOverlay.loadTile"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This class overrides the default "},{"type":"codeVoice","code":"MKTileOverlay"},{"type":"text","text":"to provide support to "},{"type":"codeVoice","code":"MapCache"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CachedTileOverlay"}],"url":"\/documentation\/mapcache\/cachedtileoverlay"},"doc://org.cocoapods.MapCache/documentation/MapCache":{"role":"collection","title":"MapCache","abstract":[],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache","kind":"symbol","type":"topic","url":"\/documentation\/mapcache"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"loadTileAtPath:result:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadTileAtPath:result:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"loadTileAtPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKTileOverlayPath","preciseIdentifier":"c:@SA@MKTileOverlayPath"},{"kind":"text","text":")"},{"kind":"internalParam","text":"path"},{"kind":"text","text":" "},{"kind":"identifier","text":"result:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSData *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSData#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"result"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlay~1loadTile(at:result:)\/title","value":"loadTileAtPath:result:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlay~1loadTile(at:result:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadTileAtPath:result:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlay\/title","value":"CachedTileOverlay"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlay\/fragments","value":[{"kind":"identifier","text":"CachedTileOverlay"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}