{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forTilePath"},{"kind":"text","text":" "},{"kind":"internalParam","text":"path"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKTileOverlayPath","preciseIdentifier":"c:@SA@MKTileOverlayPath"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapcache\/cachedtileoverlay\/url(fortilepath:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapcache\/cachedtileoverlay\/url(fortilepath:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay\/url(forTilePath:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Generates the URL for the tile to be requested."},{"type":"text","text":" "},{"type":"text","text":"It replaces the values of {z},{x} and {y} in the "},{"type":"codeVoice","code":"urlTemplate"},{"type":"text","text":"defined in "},{"type":"codeVoice","code":"mapCache.config"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forTilePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKTileOverlayPath","preciseIdentifier":"c:@SA@MKTileOverlayPath"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}],"title":"url(forTilePath:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@MapCache@objc(cs)CachedTileOverlay(im)URLForTilePath:","modules":[{"name":"MapCache"}],"navigatorTitle":[{"kind":"identifier","text":"URLForTilePath:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay"]]},"references":{"doc://org.cocoapods.MapCache/documentation/MapCache/CachedTileOverlay/url(forTilePath:)":{"role":"symbol","title":"url(forTilePath:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forTilePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKTileOverlayPath","preciseIdentifier":"c:@SA@MKTileOverlayPath"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}],"abstract":[{"type":"text","text":"Generates the URL for the tile to be requested."},{"type":"text","text":" "},{"type":"text","text":"It replaces the values of {z},{x} and {y} in the "},{"type":"codeVoice","code":"urlTemplate"},{"type":"text","text":"defined in "},{"type":"codeVoice","code":"mapCache.config"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay\/url(forTilePath:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"URLForTilePath:"}],"url":"\/documentation\/mapcache\/cachedtileoverlay\/url(fortilepath:)"},"doc://org.cocoapods.MapCache/documentation/MapCache":{"role":"collection","title":"MapCache","abstract":[],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache","kind":"symbol","type":"topic","url":"\/documentation\/mapcache"},"doc://org.cocoapods.MapCache/documentation/MapCache/CachedTileOverlay":{"role":"symbol","title":"CachedTileOverlay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CachedTileOverlay"}],"abstract":[{"type":"text","text":"Whenever a tile is requested by the "},{"type":"codeVoice","code":"MapView"},{"type":"text","text":", it calls the "},{"type":"codeVoice","code":"MKTileOverlay.loadTile"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This class overrides the default "},{"type":"codeVoice","code":"MKTileOverlay"},{"type":"text","text":"to provide support to "},{"type":"codeVoice","code":"MapCache"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CachedTileOverlay"}],"url":"\/documentation\/mapcache\/cachedtileoverlay"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"URLForTilePath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"URLForTilePath:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"URLForTilePath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKTileOverlayPath","preciseIdentifier":"c:@SA@MKTileOverlayPath"},{"kind":"text","text":")"},{"kind":"internalParam","text":"path"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlay~1url(forTilePath:)\/title","value":"URLForTilePath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlay~1url(forTilePath:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"URLForTilePath:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlay\/title","value":"CachedTileOverlay"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlay\/fragments","value":[{"kind":"identifier","text":"CachedTileOverlay"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}