{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXEmail","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXEmail","text":"GPXEmail"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxperson\/email"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPerson\/email","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The email address of the person who has created the GPX file."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXEmail","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXEmail"},{"kind":"text","text":"?"}],"title":"email","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7CoreGPX9GPXPersonC5emailAA8GPXEmailCSgvp","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPerson"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXPerson/email":{"role":"symbol","title":"email","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXEmail","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXEmail"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The email address of the person who has created the GPX file."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPerson\/email","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxperson\/email"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXPerson":{"role":"symbol","title":"GPXPerson","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXPerson"}],"abstract":[{"type":"text","text":"A value type that is designated to hold information regarding the person or organisation who has created the GPX file."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXPerson","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXPerson"}],"url":"\/documentation\/coregpx\/gpxperson"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXEmail":{"role":"symbol","title":"GPXEmail","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXEmail"}],"abstract":[{"type":"text","text":"Used for handling email types"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXEmail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXEmail"}],"url":"\/documentation\/coregpx\/gpxemail"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPerson\/title","value":"GPXPerson"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXPerson\/fragments","value":[{"kind":"identifier","text":"GPXPerson"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXEmail\/title","value":"GPXEmail"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXEmail\/fragments","value":[{"kind":"identifier","text":"GPXEmail"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}