{"variants":[{"paths":["\/documentation\/mapcache"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapcache"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/DiskCache","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/MapCache","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/TileCoords","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/TileCoordsRegion"]},{"title":"Protocols","identifiers":["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/MapCacheProtocol","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloaderDelegate"]},{"title":"Structures","identifiers":["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/Log","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/MapCacheConfig","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/TileRange","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/TileRangeIterator","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/ZoomRange","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/ZoomRangeIterator","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/ZoomableTile"]},{"title":"Type Aliases","identifiers":["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/TileNumber","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/Zoom"]},{"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/LatitudeError","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/LoadTileMode","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/LongitudeError","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/TileError","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/TileRangeError","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/ZoomError"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"MapCache","title":"MapCache","symbolKind":"module","role":"collection","modules":[{"name":"MapCache"}]},"hierarchy":{"paths":[[]]},"references":{"doc://org.cocoapods.MapCache/documentation/MapCache/MapCache":{"role":"symbol","title":"MapCache","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapCache"}],"abstract":[{"type":"text","text":"This is the main implementation of the MapCacheProtocol, the actual cache"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/MapCache","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapCache"}],"url":"\/documentation\/mapcache\/mapcache"},"doc://org.cocoapods.MapCache/documentation/MapCache":{"role":"collection","title":"MapCache","abstract":[],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache","kind":"symbol","type":"topic","url":"\/documentation\/mapcache"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloaderDelegate":{"role":"symbol","title":"RegionDownloaderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegionDownloaderDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol of "},{"type":"codeVoice","code":"RegionDownloader"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Implement this protocol whenever  you use "},{"type":"codeVoice","code":"RegionDownloader"},{"type":"text","text":" it drovides feedback while donwloading a"},{"type":"text","text":" "},{"type":"text","text":"region (f.i, downloaded %) and callsback the delegate once the download finished."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloaderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RegionDownloaderDelegate"}],"url":"\/documentation\/mapcache\/regiondownloaderdelegate"},"doc://org.cocoapods.MapCache/documentation/MapCache/CachedTileOverlay":{"role":"symbol","title":"CachedTileOverlay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CachedTileOverlay"}],"abstract":[{"type":"text","text":"Whenever a tile is requested by the "},{"type":"codeVoice","code":"MapView"},{"type":"text","text":", it calls the "},{"type":"codeVoice","code":"MKTileOverlay.loadTile"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This class overrides the default "},{"type":"codeVoice","code":"MKTileOverlay"},{"type":"text","text":"to provide support to "},{"type":"codeVoice","code":"MapCache"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CachedTileOverlay"}],"url":"\/documentation\/mapcache\/cachedtileoverlay"},"doc://org.cocoapods.MapCache/documentation/MapCache/TileRange":{"role":"symbol","title":"TileRange","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRange"}],"abstract":[{"type":"text","text":"For a particular zoom level, defines a range of tiles."},{"type":"text","text":" "},{"type":"text","text":"It can be iterated in a for loop. It will get the `TileCoord``"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/TileRange","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileRange"}],"url":"\/documentation\/mapcache\/tilerange"},"https://github.com/Haneke/HanekeSwift":{"title":"Haneke Disk Cache","titleInlineContent":[{"type":"text","text":"Haneke Disk Cache"}],"type":"link","identifier":"https:\/\/github.com\/Haneke\/HanekeSwift","url":"https:\/\/github.com\/Haneke\/HanekeSwift"},"doc://org.cocoapods.MapCache/documentation/MapCache/MapCacheConfig":{"role":"symbol","title":"MapCacheConfig","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapCacheConfig"}],"abstract":[{"type":"text","text":"Settings of your MapCache."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/MapCacheConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapCacheConfig"}],"url":"\/documentation\/mapcache\/mapcacheconfig"},"doc://org.cocoapods.MapCache/documentation/MapCache/MapCacheProtocol":{"role":"symbol","title":"MapCacheProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapCacheProtocol"}],"abstract":[{"type":"text","text":"This protocol shall be implemented by any cache used in MapCache."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/MapCacheProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapCacheProtocol"}],"url":"\/documentation\/mapcache\/mapcacheprotocol"},"doc://org.cocoapods.MapCache/documentation/MapCache/ZoomRangeIterator":{"role":"symbol","title":"ZoomRangeIterator","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZoomRangeIterator"}],"abstract":[{"type":"text","text":"Iterator that allows the use of ZoomRange in a for loop."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/ZoomRangeIterator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZoomRangeIterator"}],"url":"\/documentation\/mapcache\/zoomrangeiterator"},"doc://org.cocoapods.MapCache/documentation/MapCache/TileNumber":{"role":"symbol","title":"TileNumber","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileNumber"}],"abstract":[{"type":"text","text":"Tile number in a map."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/TileNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileNumber"}],"url":"\/documentation\/mapcache\/tilenumber"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader":{"role":"symbol","title":"RegionDownloader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegionDownloader"}],"abstract":[{"type":"text","text":"Hey! I need to download this area of the map."},{"type":"text","text":" "},{"type":"text","text":"No problemo."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RegionDownloader"}],"url":"\/documentation\/mapcache\/regiondownloader"},"doc://org.cocoapods.MapCache/documentation/MapCache/Log":{"role":"symbol","title":"Log","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Log"}],"abstract":[{"type":"text","text":"For logging messages on console."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/Log","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Log"}],"url":"\/documentation\/mapcache\/log"},"doc://org.cocoapods.MapCache/documentation/MapCache/MapCacheVersionNumber":{"role":"symbol","title":"MapCacheVersionNumber","fragments":[{"kind":"identifier","text":"MapCacheVersionNumber"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/MapCacheVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/mapcache\/mapcacheversionnumber"},"doc://org.cocoapods.MapCache/documentation/MapCache/ZoomRange":{"role":"symbol","title":"ZoomRange","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZoomRange"}],"abstract":[{"type":"text","text":"A range of zooms."},{"type":"text","text":" "},{"type":"text","text":"Matematically: [z1, z1+1, z1+2,…, z2-1, z2]"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/ZoomRange","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZoomRange"}],"url":"\/documentation\/mapcache\/zoomrange"},"doc://org.cocoapods.MapCache/documentation/MapCache/ZoomableTile":{"role":"symbol","title":"ZoomableTile","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZoomableTile"}],"abstract":[{"type":"text","text":"Specifies a single tile and area of the tile that should upscaled."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/ZoomableTile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZoomableTile"}],"url":"\/documentation\/mapcache\/zoomabletile"},"doc://org.cocoapods.MapCache/documentation/MapCache/LongitudeError":{"role":"symbol","title":"LongitudeError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LongitudeError"}],"abstract":[{"type":"text","text":"Errors for a longitude."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/LongitudeError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LongitudeError"}],"url":"\/documentation\/mapcache\/longitudeerror"},"doc://org.cocoapods.MapCache/documentation/MapCache/TileCoords":{"role":"symbol","title":"TileCoords","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCoords"}],"abstract":[{"type":"text","text":"Class to convert from Map Tiles to coordinates and from coordinates to tiles"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/TileCoords","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileCoords"}],"url":"\/documentation\/mapcache\/tilecoords"},"doc://org.cocoapods.MapCache/documentation/MapCache/MapCacheVersionString":{"role":"symbol","title":"MapCacheVersionString","fragments":[{"kind":"identifier","text":"MapCacheVersionString"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/MapCacheVersionString","kind":"symbol","type":"topic","url":"\/documentation\/mapcache\/mapcacheversionstring"},"doc://org.cocoapods.MapCache/documentation/MapCache/ZoomError":{"role":"symbol","title":"ZoomError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZoomError"}],"abstract":[{"type":"text","text":"Errors for Zoom."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/ZoomError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZoomError"}],"url":"\/documentation\/mapcache\/zoomerror"},"doc://org.cocoapods.MapCache/documentation/MapCache/LatitudeError":{"role":"symbol","title":"LatitudeError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LatitudeError"}],"abstract":[{"type":"text","text":"Errors for a latitude."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/LatitudeError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LatitudeError"}],"url":"\/documentation\/mapcache\/latitudeerror"},"doc://org.cocoapods.MapCache/documentation/MapCache/LoadTileMode":{"role":"symbol","title":"LoadTileMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoadTileMode"}],"abstract":[{"type":"text","text":"Defines the strategies that can be used for retrieving the tiles from the cache"},{"type":"text","text":" "},{"type":"text","text":"Used by "},{"type":"codeVoice","code":"MapCache.loadTile()"},{"type":"text","text":" method."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/LoadTileMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoadTileMode"}],"url":"\/documentation\/mapcache\/loadtilemode"},"doc://org.cocoapods.MapCache/documentation/MapCache/Zoom":{"role":"symbol","title":"Zoom","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Zoom"}],"abstract":[{"type":"text","text":"An alias for UInt8. Used to indicate that the variable is holding a zoom value."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/Zoom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Zoom"}],"url":"\/documentation\/mapcache\/zoom"},"doc://org.cocoapods.MapCache/documentation/MapCache/TileError":{"role":"symbol","title":"TileError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileError"}],"abstract":[{"type":"text","text":"Errors for a tile"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/TileError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileError"}],"url":"\/documentation\/mapcache\/tileerror"},"doc://org.cocoapods.MapCache/documentation/MapCache/TileRangeError":{"role":"symbol","title":"TileRangeError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRangeError"}],"abstract":[{"type":"text","text":"Errors for tile range"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/TileRangeError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileRangeError"}],"url":"\/documentation\/mapcache\/tilerangeerror"},"doc://org.cocoapods.MapCache/documentation/MapCache/TileRangeIterator":{"role":"symbol","title":"TileRangeIterator","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRangeIterator"}],"abstract":[{"type":"text","text":"Iterator of a TileRange."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/TileRangeIterator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileRangeIterator"}],"url":"\/documentation\/mapcache\/tilerangeiterator"},"doc://org.cocoapods.MapCache/documentation/MapCache/CachedTileOverlayRenderer":{"role":"symbol","title":"CachedTileOverlayRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CachedTileOverlayRenderer"}],"abstract":[{"type":"text","text":"A Tile overlay that supports to zoom beyond the maximumZ"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CachedTileOverlayRenderer"}],"url":"\/documentation\/mapcache\/cachedtileoverlayrenderer"},"doc://org.cocoapods.MapCache/documentation/MapCache/TileCoordsRegion":{"role":"symbol","title":"TileCoordsRegion","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCoordsRegion"}],"abstract":[{"type":"text","text":"3 dimensional square region in a tile map."},{"type":"text","text":" "},{"type":"text","text":"The three dimensions are:"}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/TileCoordsRegion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileCoordsRegion"}],"url":"\/documentation\/mapcache\/tilecoordsregion"},"doc://org.cocoapods.MapCache/documentation/MapCache/DiskCache":{"role":"symbol","title":"DiskCache","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiskCache"}],"abstract":[{"type":"text","text":"A specialized cache for storing data in disk."},{"type":"text","text":" "},{"type":"text","text":"Based on "},{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/Haneke\/HanekeSwift"},{"type":"text","text":" and customized for the MapCache project."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/DiskCache","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiskCache"}],"url":"\/documentation\/mapcache\/diskcache"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlay","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/CachedTileOverlayRenderer","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader"]},{"title":"Protocols","identifiers":["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloaderDelegate"]},{"title":"Variables","identifiers":["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/MapCacheVersionNumber","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/MapCacheVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloaderDelegate\/title","value":"RegionDownloaderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloaderDelegate\/fragments","value":[{"kind":"identifier","text":"RegionDownloaderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlay\/title","value":"CachedTileOverlay"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlay\/fragments","value":[{"kind":"identifier","text":"CachedTileOverlay"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloader\/title","value":"RegionDownloader"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloader\/fragments","value":[{"kind":"identifier","text":"RegionDownloader"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlayRenderer\/title","value":"CachedTileOverlayRenderer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1CachedTileOverlayRenderer\/fragments","value":[{"kind":"identifier","text":"CachedTileOverlayRenderer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}