{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxroutepoint\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/coregpx\/gpxroutepoint\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoutePoint\/init()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Default initializer"}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@CoreGPX@objc(cs)GPXRoutePoint(im)init","modules":[{"name":"CoreGPX"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoutePoint"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoutePoint":{"role":"symbol","title":"GPXRoutePoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXRoutePoint"}],"abstract":[{"type":"text","text":"A route point is just like a waypoint or track point, but is suited to be part of a route."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoutePoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXRoutePoint"}],"url":"\/documentation\/coregpx\/gpxroutepoint"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXRoutePoint/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Default initializer"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXRoutePoint\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/coregpx\/gpxroutepoint\/init()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoutePoint\/title","value":"GPXRoutePoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoutePoint\/fragments","value":[{"kind":"identifier","text":"GPXRoutePoint"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoutePoint~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXRoutePoint~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}