{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"points"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoutePoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLegacyRoutePoint","text":"GPXLegacyRoutePoint"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxlegacyroute\/points"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoute\/points","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"points"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXLegacyRoutePoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLegacyRoutePoint"},{"kind":"text","text":"]"}],"title":"points","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7CoreGPX14GPXLegacyRouteC6pointsSayAA0cD5PointCGvp","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoute"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoute":{"role":"symbol","title":"GPXLegacyRoute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyRoute"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyRoute"}],"url":"\/documentation\/coregpx\/gpxlegacyroute"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoute/points":{"role":"symbol","title":"points","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"points"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXLegacyRoutePoint","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLegacyRoutePoint"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoute\/points","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxlegacyroute\/points"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLegacyRoutePoint":{"role":"symbol","title":"GPXLegacyRoutePoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLegacyRoutePoint"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLegacyRoutePoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLegacyRoutePoint"}],"url":"\/documentation\/coregpx\/gpxlegacyroutepoint"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoute\/title","value":"GPXLegacyRoute"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoute\/fragments","value":[{"kind":"identifier","text":"GPXLegacyRoute"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoutePoint\/title","value":"GPXLegacyRoutePoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLegacyRoutePoint\/fragments","value":[{"kind":"identifier","text":"GPXLegacyRoutePoint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}