{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"children"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensionsElement","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXExtensionsElement","text":"GPXExtensionsElement"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxextensions\/children"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensions\/children","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Extended children tags"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"children"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXExtensionsElement","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXExtensionsElement"},{"kind":"text","text":"]"}],"title":"children","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7CoreGPX13GPXExtensionsC8childrenSayAA0C7ElementCGvp","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensions"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXExtensions/children":{"role":"symbol","title":"children","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"children"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXExtensionsElement","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXExtensionsElement"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Extended children tags"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensions\/children","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxextensions\/children"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXExtensions":{"role":"symbol","title":"GPXExtensions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXExtensions"}],"abstract":[{"type":"text","text":"For adding\/obtaining data stored as extensions in GPX file."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXExtensions"}],"url":"\/documentation\/coregpx\/gpxextensions"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXExtensionsElement":{"role":"symbol","title":"GPXExtensionsElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXExtensionsElement"}],"abstract":[{"type":"text","text":"A duplicated class of "},{"type":"codeVoice","code":"GPXRawElement"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensionsElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXExtensionsElement"}],"url":"\/documentation\/coregpx\/gpxextensionselement"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensions\/title","value":"GPXExtensions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensions\/fragments","value":[{"kind":"identifier","text":"GPXExtensions"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensionsElement\/title","value":"GPXExtensionsElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensionsElement\/fragments","value":[{"kind":"identifier","text":"GPXExtensionsElement"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}