{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"subscript"},{"kind":"text","text":"("},{"kind":"internalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensionsElement","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXExtensionsElement","text":"GPXExtensionsElement"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"name","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"name of child tag."}]}]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If extended data does not have a parent tag, "},{"type":"strong","inlineContent":[{"type":"text","text":"i.e"}]},{"type":"text","text":":"}]},{"type":"codeListing","syntax":null,"code":["   <extensions>","       <tag>50<\/tag>","   <\/extensions>"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Access it directly by "},{"type":"codeVoice","code":"extensions[\"tag\"]"},{"type":"text","text":", and access the text attribute of it."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If extended data does not have a parent tag, "},{"type":"strong","inlineContent":[{"type":"text","text":"i.e"}]},{"type":"text","text":":"}]},{"type":"codeListing","syntax":null,"code":["   <ParentTag>","       <Tag>80<\/Tag>","   <\/ParentTag>"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Access it directly by "},{"type":"codeVoice","code":"extensions[\"ParentTag\"][\"tag\"]"},{"type":"text","text":", and access the text attribute of it."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxextensions\/subscript(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensions\/subscript(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Access child element in extensions."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"subscript"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GPXExtensionsElement","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXExtensionsElement"}],"title":"subscript(_:)","roleHeading":"Instance Subscript","role":"symbol","symbolKind":"subscript","externalID":"s:7CoreGPX13GPXExtensionsCyAA0C7ElementCSScip","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensions"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXExtensionsElement":{"role":"symbol","title":"GPXExtensionsElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXExtensionsElement"}],"abstract":[{"type":"text","text":"A duplicated class of "},{"type":"codeVoice","code":"GPXRawElement"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensionsElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXExtensionsElement"}],"url":"\/documentation\/coregpx\/gpxextensionselement"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXExtensions/subscript(_:)":{"role":"symbol","title":"subscript(_:)","fragments":[{"kind":"keyword","text":"subscript"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GPXExtensionsElement","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXExtensionsElement"}],"abstract":[{"type":"text","text":"Access child element in extensions."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensions\/subscript(_:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxextensions\/subscript(_:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXExtensions":{"role":"symbol","title":"GPXExtensions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXExtensions"}],"abstract":[{"type":"text","text":"For adding\/obtaining data stored as extensions in GPX file."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXExtensions"}],"url":"\/documentation\/coregpx\/gpxextensions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensionsElement\/title","value":"GPXExtensionsElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensionsElement\/fragments","value":[{"kind":"identifier","text":"GPXExtensionsElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensions\/title","value":"GPXExtensions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensions\/fragments","value":[{"kind":"identifier","text":"GPXExtensions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}