{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extensions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensions","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXExtensions","text":"GPXExtensions"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxwaypoint\/extensions"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/extensions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Extension to GPX v1.1 standard."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extensions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXExtensions","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXExtensions"},{"kind":"text","text":"?"}],"title":"extensions","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7CoreGPX11GPXWaypointC10extensionsAA13GPXExtensionsCSgvp","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXExtensions":{"role":"symbol","title":"GPXExtensions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXExtensions"}],"abstract":[{"type":"text","text":"For adding\/obtaining data stored as extensions in GPX file."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXExtensions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXExtensions"}],"url":"\/documentation\/coregpx\/gpxextensions"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/extensions":{"role":"symbol","title":"extensions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extensions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXExtensions","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXExtensions"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Extension to GPX v1.1 standard."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/extensions","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxwaypoint\/extensions"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint":{"role":"symbol","title":"GPXWaypoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXWaypoint"}],"abstract":[{"type":"text","text":"A value type that represents waypoint based off GPX v1.1 schema’s "},{"type":"codeVoice","code":"wptType"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXWaypoint"}],"url":"\/documentation\/coregpx\/gpxwaypoint"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensions\/title","value":"GPXExtensions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXExtensions\/fragments","value":[{"kind":"identifier","text":"GPXExtensions"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXWaypoint\/title","value":"GPXWaypoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXWaypoint\/fragments","value":[{"kind":"identifier","text":"GPXWaypoint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}