{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The waypoint should be configured appropriately after initializing using this initializer. The "},{"type":"codeVoice","code":"time"},{"type":"text","text":" attribute will also be set to the time of initializing."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxwaypoint\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/coregpx\/gpxwaypoint\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/init()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initialize with current date and time"}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@CoreGPX@objc(cs)GPXWaypoint(im)init","modules":[{"name":"CoreGPX"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Initialize with current date and time"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/coregpx\/gpxwaypoint\/init()"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint":{"role":"symbol","title":"GPXWaypoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXWaypoint"}],"abstract":[{"type":"text","text":"A value type that represents waypoint based off GPX v1.1 schema’s "},{"type":"codeVoice","code":"wptType"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXWaypoint"}],"url":"\/documentation\/coregpx\/gpxwaypoint"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXWaypoint~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXWaypoint~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXWaypoint\/title","value":"GPXWaypoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXWaypoint\/fragments","value":[{"kind":"identifier","text":"GPXWaypoint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}