{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newLink"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withHref"},{"kind":"text","text":" "},{"kind":"internalParam","text":"href"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLink","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLink","text":"GPXLink"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"href","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"a URL hyperlink as a "},{"type":"codeVoice","code":"String"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method works by initializing a new "},{"type":"codeVoice","code":"GPXLink"},{"type":"text","text":", adding to this point type, then return the "},{"type":"codeVoice","code":"GPXLink"}]},{"style":"warning","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Will be deprecated starting version 0.5.0"}]}],"type":"aside","name":"Warning"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxwaypoint\/newlink(withhref:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/newLink(withHref:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"for initializing a "},{"type":"codeVoice","code":"GPXLink"},{"type":"text","text":" with href, which is added to this point type as well."}],"kind":"symbol","metadata":{"role":"symbol","title":"newLink(withHref:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newLink"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withHref"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GPXLink","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLink"}],"symbolKind":"method","externalID":"s:7CoreGPX11GPXWaypointC7newLink8withHrefAA7GPXLinkCSS_tF","modules":[{"name":"CoreGPX"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Initialize GPXLink first then, add it to this point type instead."}]}],"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLink":{"role":"symbol","title":"GPXLink","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLink"}],"abstract":[{"type":"text","text":"A value type that can hold a web link to a external resource, or external information about a certain attribute."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLink","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLink"}],"url":"\/documentation\/coregpx\/gpxlink"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint/newLink(withHref:)":{"role":"symbol","title":"newLink(withHref:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newLink"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withHref"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GPXLink","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLink"}],"abstract":[{"type":"text","text":"for initializing a "},{"type":"codeVoice","code":"GPXLink"},{"type":"text","text":" with href, which is added to this point type as well."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint\/newLink(withHref:)","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/coregpx\/gpxwaypoint\/newlink(withhref:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXWaypoint":{"role":"symbol","title":"GPXWaypoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXWaypoint"}],"abstract":[{"type":"text","text":"A value type that represents waypoint based off GPX v1.1 schema’s "},{"type":"codeVoice","code":"wptType"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXWaypoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXWaypoint"}],"url":"\/documentation\/coregpx\/gpxwaypoint"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLink\/title","value":"GPXLink"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLink\/fragments","value":[{"kind":"identifier","text":"GPXLink"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXWaypoint\/title","value":"GPXWaypoint"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXWaypoint\/fragments","value":[{"kind":"identifier","text":"GPXWaypoint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}