{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"regionDownloader"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"regionDownloader"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader","preciseIdentifier":"c:@M@MapCache@objc(cs)RegionDownloader","text":"RegionDownloader"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDownloadPercentage"},{"kind":"text","text":" "},{"kind":"internalParam","text":"percentage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapcache\/regiondownloaderdelegate\/regiondownloader(_:diddownloadpercentage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapcache\/regiondownloaderdelegate\/regiondownloader(_:diddownloadpercentage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloaderDelegate\/regionDownloader(_:didDownloadPercentage:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Did download the percentage."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"regionDownloader:didDownloadPercentage:"}],"role":"symbol","title":"regionDownloader(_:didDownloadPercentage:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"regionDownloader"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RegionDownloader","preciseIdentifier":"c:@M@MapCache@objc(cs)RegionDownloader"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDownloadPercentage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@MapCache@objc(pl)RegionDownloaderDelegate(im)regionDownloader:didDownloadPercentage:","required":true,"modules":[{"name":"MapCache"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache","doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloaderDelegate"]]},"references":{"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloaderDelegate/regionDownloader(_:didDownloadPercentage:)":{"navigatorTitle":[{"kind":"identifier","text":"regionDownloader:didDownloadPercentage:"}],"role":"symbol","title":"regionDownloader(_:didDownloadPercentage:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"regionDownloader"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RegionDownloader","preciseIdentifier":"c:@M@MapCache@objc(cs)RegionDownloader"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDownloadPercentage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Did download the percentage."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloaderDelegate\/regionDownloader(_:didDownloadPercentage:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapcache\/regiondownloaderdelegate\/regiondownloader(_:diddownloadpercentage:)"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloaderDelegate":{"role":"symbol","title":"RegionDownloaderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegionDownloaderDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol of "},{"type":"codeVoice","code":"RegionDownloader"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Implement this protocol whenever  you use "},{"type":"codeVoice","code":"RegionDownloader"},{"type":"text","text":" it drovides feedback while donwloading a"},{"type":"text","text":" "},{"type":"text","text":"region (f.i, downloaded %) and callsback the delegate once the download finished."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloaderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RegionDownloaderDelegate"}],"url":"\/documentation\/mapcache\/regiondownloaderdelegate"},"doc://org.cocoapods.MapCache/documentation/MapCache/RegionDownloader":{"role":"symbol","title":"RegionDownloader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegionDownloader"}],"abstract":[{"type":"text","text":"Hey! I need to download this area of the map."},{"type":"text","text":" "},{"type":"text","text":"No problemo."}],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RegionDownloader"}],"url":"\/documentation\/mapcache\/regiondownloader"},"doc://org.cocoapods.MapCache/documentation/MapCache":{"role":"collection","title":"MapCache","abstract":[],"identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache","kind":"symbol","type":"topic","url":"\/documentation\/mapcache"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"regionDownloader:didDownloadPercentage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"regionDownloader:didDownloadPercentage:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"regionDownloader:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.MapCache\/documentation\/MapCache\/RegionDownloader","preciseIdentifier":"c:@M@MapCache@objc(cs)RegionDownloader","text":"RegionDownloader"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"regionDownloader"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDownloadPercentage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":")"},{"kind":"internalParam","text":"percentage"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloaderDelegate~1regionDownloader(_:didDownloadPercentage:)\/title","value":"regionDownloader:didDownloadPercentage:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloaderDelegate~1regionDownloader(_:didDownloadPercentage:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"regionDownloader:didDownloadPercentage:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloaderDelegate\/title","value":"RegionDownloaderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloaderDelegate\/fragments","value":[{"kind":"identifier","text":"RegionDownloaderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloader\/title","value":"RegionDownloader"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.MapCache~1documentation~1MapCache~1RegionDownloader\/fragments","value":[{"kind":"identifier","text":"RegionDownloader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}