{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"link"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLink","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLink","text":"GPXLink"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Intended for additional information about current route through a web link."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxtrack\/link"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/link","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A value type for link properties (see "},{"type":"codeVoice","code":"GPXLink"},{"type":"text","text":")"}],"kind":"symbol","metadata":{"role":"symbol","title":"link","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"link"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXLink","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLink"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"s:7CoreGPX8GPXTrackC4linkAA7GPXLinkCSgvp","modules":[{"name":"CoreGPX"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"CoreGPX now support multiple links."}]}],"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack":{"role":"symbol","title":"GPXTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrack"}],"abstract":[{"type":"text","text":"Represents "},{"type":"codeVoice","code":"trkType"},{"type":"text","text":" of GPX v1.1 schema."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXTrack"}],"url":"\/documentation\/coregpx\/gpxtrack"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/link":{"role":"symbol","title":"link","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"link"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GPXLink","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLink"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A value type for link properties (see "},{"type":"codeVoice","code":"GPXLink"},{"type":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/link","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/coregpx\/gpxtrack\/link"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLink":{"role":"symbol","title":"GPXLink","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLink"}],"abstract":[{"type":"text","text":"A value type that can hold a web link to a external resource, or external information about a certain attribute."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLink","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLink"}],"url":"\/documentation\/coregpx\/gpxlink"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrack\/title","value":"GPXTrack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrack\/fragments","value":[{"kind":"identifier","text":"GPXTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLink\/title","value":"GPXLink"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLink\/fragments","value":[{"kind":"identifier","text":"GPXLink"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}