{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newLink"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withHref"},{"kind":"text","text":" "},{"kind":"internalParam","text":"href"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLink","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLink","text":"GPXLink"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Method not recommended for use. Please initialize "},{"type":"codeVoice","code":"GPXLink"},{"type":"text","text":" manually and adding it to the track instead."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxtrack\/newlink(withhref:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/newLink(withHref:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initialize a new "},{"type":"codeVoice","code":"GPXLink"},{"type":"text","text":" to the track."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newLink"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withHref"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GPXLink","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLink"}],"title":"newLink(withHref:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:7CoreGPX8GPXTrackC7newLink8withHrefAA7GPXLinkCSS_tF","modules":[{"name":"CoreGPX"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack":{"role":"symbol","title":"GPXTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrack"}],"abstract":[{"type":"text","text":"Represents "},{"type":"codeVoice","code":"trkType"},{"type":"text","text":" of GPX v1.1 schema."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXTrack"}],"url":"\/documentation\/coregpx\/gpxtrack"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/newLink(withHref:)":{"role":"symbol","title":"newLink(withHref:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newLink"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withHref"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GPXLink","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXLink"}],"abstract":[{"type":"text","text":"Initialize a new "},{"type":"codeVoice","code":"GPXLink"},{"type":"text","text":" to the track."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/newLink(withHref:)","kind":"symbol","type":"topic","url":"\/documentation\/coregpx\/gpxtrack\/newlink(withhref:)"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXLink":{"role":"symbol","title":"GPXLink","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXLink"}],"abstract":[{"type":"text","text":"A value type that can hold a web link to a external resource, or external information about a certain attribute."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXLink","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXLink"}],"url":"\/documentation\/coregpx\/gpxlink"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrack\/title","value":"GPXTrack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrack\/fragments","value":[{"kind":"identifier","text":"GPXTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLink\/title","value":"GPXLink"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXLink\/fragments","value":[{"kind":"identifier","text":"GPXLink"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}