{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tracksegments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackSegment","text":"GPXTrackSegment"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coregpx\/gpxtrack\/tracksegments"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/tracksegments","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Array of track segments. Must be included in every track."}],"kind":"symbol","metadata":{"role":"symbol","title":"tracksegments","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tracksegments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXTrackSegment","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackSegment"},{"kind":"text","text":"]"}],"symbolKind":"property","externalID":"s:7CoreGPX8GPXTrackC13tracksegmentsSayAA0C7SegmentCGvp","modules":[{"name":"CoreGPX"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack"]]},"references":{"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrackSegment":{"role":"symbol","title":"GPXTrackSegment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrackSegment"}],"abstract":[{"type":"text","text":"A track segment that holds data on all track points in the particular segment."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrackSegment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXTrackSegment"}],"url":"\/documentation\/coregpx\/gpxtracksegment"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX":{"role":"collection","title":"CoreGPX","abstract":[],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX","kind":"symbol","type":"topic","url":"\/documentation\/coregpx"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack":{"role":"symbol","title":"GPXTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPXTrack"}],"abstract":[{"type":"text","text":"Represents "},{"type":"codeVoice","code":"trkType"},{"type":"text","text":" of GPX v1.1 schema."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPXTrack"}],"url":"\/documentation\/coregpx\/gpxtrack"},"doc://org.cocoapods.CoreGPX/documentation/CoreGPX/GPXTrack/tracksegments":{"role":"symbol","title":"tracksegments","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tracksegments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GPXTrackSegment","preciseIdentifier":"c:@M@CoreGPX@objc(cs)GPXTrackSegment"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Array of track segments. Must be included in every track."}],"identifier":"doc:\/\/org.cocoapods.CoreGPX\/documentation\/CoreGPX\/GPXTrack\/tracksegments","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/coregpx\/gpxtrack\/tracksegments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackSegment\/title","value":"GPXTrackSegment"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrackSegment\/fragments","value":[{"kind":"identifier","text":"GPXTrackSegment"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrack\/title","value":"GPXTrack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreGPX~1documentation~1CoreGPX~1GPXTrack\/fragments","value":[{"kind":"identifier","text":"GPXTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}